---
sidebar: sidebar 
permalink: integrations/dashboard-overview.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console 
summary: In qualità di abbonato a NetApp Keystone STaaS, puoi ottenere una panoramica dei tuoi abbonamenti da NetApp Console o Digital Advisor. 
---
= Scopri di più sulla dashboard Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La dashboard Keystone è la soluzione ideale per monitorare, analizzare e gestire in modo efficiente i tuoi abbonamenti Keystone. Grazie alla dashboard Keystone, puoi raggiungere i seguenti obiettivi:

* *Monitoraggio dei dettagli dell'abbonamento*: visualizza informazioni dettagliate sui tuoi abbonamenti Keystone, inclusi livelli di servizio delle prestazioni, utilizzo della capacità, risorse e avvisi.
* *Monitoraggio dell'utilizzo della capacità e generazione di report*: tieni traccia dell'utilizzo attuale e storico della capacità e genera report per analizzare i dati degli abbonamenti e prendere decisioni informate.
* *Visualizza la cronologia degli abbonamenti*: rimani informato sulle date e gli eventi principali monitorando la cronologia dei tuoi abbonamenti.
* *Gestisci abbonamenti*: invia richieste di modifica dei livelli di servizio delle prestazioni o di altri parametri di abbonamento in base alle tue esigenze.
* *Analizza volumi e oggetti*: ottieni informazioni dettagliate sui volumi e sugli oggetti dei tuoi abbonamenti, inclusa la loro capacità sia a livello di volume che di oggetto.




== Accedi alla dashboard Keystone

È possibile accedere alla dashboard Keystone tramite:

* * Console NetApp *: accedi alla dashboard da *Storage > Keystone > Panoramica* nella Console. Per saperne di più, fare riferimento alink:../integrations/keystone-console.html["Dashboard Keystone nella console NetApp"^] .
* *Active IQ Digital Advisor* (noto anche come Digital Advisor): accedi alla dashboard da *Generale > Abbonamenti Keystone* in Digital Advisor. Per ulteriori informazioni, fare riferimento a link:../integrations/keystone-aiq.html["Dashboard Keystone in Digital Advisor"^].




== Informazioni su NetApp Console

Keystone è accessibile tramite la console NetApp .

NetApp Console offre una gestione centralizzata dei servizi di archiviazione e dati NetApp in ambienti on-premise e cloud su scala aziendale. La console è necessaria per accedere e utilizzare i servizi dati NetApp . In quanto interfaccia di gestione, consente di gestire numerose risorse di archiviazione da un'unica interfaccia. Gli amministratori della console possono controllare l'accesso allo storage e ai servizi per tutti i sistemi all'interno dell'azienda.

Per iniziare a utilizzare la Console non è necessaria una licenza o un abbonamento e verranno addebitati dei costi solo quando sarà necessario distribuire gli agenti della Console nel cloud per garantire la connettività ai sistemi di storage o ai servizi dati NetApp . Tuttavia, alcuni servizi dati NetApp accessibili dalla Console sono concessi in licenza o basati su abbonamento.

Scopri di più sulink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Console NetApp"^] .

Tenere presente quanto segue:

* Sebbene la Console e il Digital Advisor offrano alcune funzionalità esclusive, la Console fornisce funzionalità amministrative per Keystone, consentendo di gestire gli abbonamenti e apportare le modifiche necessarie.
* Per modificare gli abbonamenti è necessario essere assegnati al ruolo di * amministratore Keystone *. Per saperne di più, fare riferimento alink:https://docs.netapp.com/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso alla console NetApp"^] .
* Digital Advisor è integrato con la Console, consentendoti di accedere a tutte le funzionalità Digital Advisor , inclusa la dashboard Keystone , direttamente dalla Console. Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console["Integrazione Digital Advisor con NetApp Console"^] .




== Funzionalità Keystone in NetApp Console e Digital Advisor

La tabella seguente mostra la disponibilità delle funzionalità nella NetApp Console e in Digital Advisor, aiutandoti a identificare rapidamente la piattaforma più adatta alle tue esigenze:

|===


| *Funzione* | * Console NetApp * | *Consulente digitale* 


 a| 
link:../integrations/subscriptions-tab.html["Visualizza i dettagli del tuo abbonamento"]
| Sì | Sì 


 a| 
link:../integrations/current-usage-tab.html["Monitorare l'utilizzo attuale e storico della capacità"]
| Sì | Sì 


 a| 
link:../integrations/subscription-timeline.html["Tieni traccia della cronologia degli abbonamenti"]
| Sì | No 


 a| 
link:../integrations/assets-tab.html["Visualizza le risorse associate a un abbonamento Keystone"]
| Sì | Sì 


| link:../integrations/assets.html["Visualizza le risorse su più abbonamenti Keystone"] | Sì | No 


 a| 
link:../integrations/monitoring-alerts.html["Visualizza e gestisci avvisi e monitor"]
| Sì | No 


 a| 
link:../integrations/modify-subscription.html["Modifica i tuoi abbonamenti"] (solo per gli amministratori Keystone)
| Sì | No 


 a| 
link:../integrations/options.html#generate-reports-from-console-or-digital-advisor["Generare report"]
| Sì | Sì 


 a| 
link:../integrations/volumes-objects-tab.html["Visualizzare i dettagli di volumi e oggetti"]
| Sì | Sì 


 a| 
link:../integrations/performance-tab.html["Visualizza le metriche delle performance"]
| No | Sì 
|===
*Informazioni correlate*

* link:../integrations/dashboard-access.html["Inizia con la dashboard Keystone"]
* link:../integrations/keystone-console.html["Dashboard Keystone nella console NetApp"]
* link:..//integrations/keystone-aiq.html["Dashboard Keystone in Digital Advisor"]

