---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Keystone e BlueXP 
---
= Scopri Keystone e BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp BlueXP è una piattaforma completa per il monitoraggio di centinaia di origini dati, con una dashboard di visualizzazione interattiva. Se acquisti un servizio cloud con il tuo abbonamento a NetApp Keystone, puoi accedere e gestire tali servizi tramite BlueXP.

La dashboard di BlueXP Digital Advisor offre una vista grafica e funzionalità di drill-down per monitorare l'utilizzo dell'abbonamento Keystone e generare report. Per ulteriori informazioni sulla dashboard di Digital Advisor e Keystone, vedere link:../integrations/aiq-keystone-details.html["Dashboard e reporting per l'abbonamento Keystone"].

In qualità di cliente Keystone, se hai un abbonamento a Cloud Volumes ONTAP, puoi utilizzare i servizi Keystone per addebitare l'utilizzo di Cloud Volumes ONTAP e visualizzare i dettagli di fatturazione e consumo tramite BlueXP.

A tale scopo, è necessario creare uno o più account BlueXP e collegarli all'account Keystone. Mentre acquisti un servizio cloud tramite Keystone, devi fornire i dettagli dei tuoi account BlueXP al tuo Keystone Success Manager (KSM). Ciò consente di misurare e addebitare correttamente l'utilizzo del servizio cloud tramite il tuo abbonamento Keystone.

Per ulteriori informazioni su Keystone e BlueXP, consultare i seguenti collegamenti nei documenti BlueXP:

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription["Iscrizione Keystone"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html["Gestisci gli abbonamenti Keystone"^]

