---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti Keystone
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità di Keystone STaaS
      url: "/whats-new.html"
    - title: Problemi risolti
      url: "/release-notes/fixed-issues.html"
    - title: Problemi noti
      url: "/release-notes/known-issues.html"
    - title: Limitazioni note
      url: "/release-notes/known-limitations.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più su Keystone STaaS
      url: "/concepts/overview.html"
    - title: Infrastruttura Keystone
      url: "/concepts/infra.html"
    - title: Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Componenti
      url: "/concepts/components.html"
    - title: Flusso di dati
      url: "/concepts/data-flow.html"
    - title: Modelli operativi
      url: "/concepts/operational-models.html"
  - title: Impostare e configurare Keystone
    entries:
    - title: Requisiti
      entries:
      - title: Infrastruttura virtuale
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP e StorageGRID
        url: "/installation/addl-req.html"
    - title: Installare Keystone Collector
      entries:
      - title: Implementazione su VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Installare su Linux
        url: "/installation/linux-installation.html"
      - title: Convalida automatica del software Keystone
        url: "/installation/validation.html"
    - title: Configurare Keystone Collector
      url: "/installation/configuration.html"
    - title: Installare ITOM Collector
      entries:
      - title: Preparazione per l'installazione
        url: "/installation/itom-prereqs.html"
      - title: Installare su Linux
        url: "/installation/install-itom-linux.html"
      - title: Installazione su Windows
        url: "/installation/install-itom-windows.html"
    - title: Configurare AutoSupport
      url: "/installation/asup-config.html"
    - title: Monitoraggio e aggiornamento
      entries:
      - title: Monitorare la salute di Keystone Collector
        url: "/installation/monitor-health.html"
      - title: Aggiorna Keystone Collector
        url: "/installation/upgrade.html"
    - title: Sicurezza di Keystone Collector
      url: "/installation/security.html"
    - title: Dati raccolti per la fatturazione
      url: "/installation/data-collection.html"
    - title: Keystone in modalità privata
      entries:
      - title: Panoramica
        url: "/dark-sites/overview.html"
      - title: Preparazione per l'installazione
        url: "/dark-sites/requirements.html"
      - title: Installare Keystone Collector
        url: "/dark-sites/install-collector.html"
      - title: Configurare Keystone Collector
        url: "/dark-sites/configure-collector.html"
      - title: Monitorare la salute di Keystone Collector
        url: "/dark-sites/monitor.html"
  - title: Gestire e monitorare gli abbonamenti Keystone
    entries:
    - title: Comprendere la dashboard Keystone
      entries:
      - title: Scopri di più sulla dashboard Keystone
        url: "/integrations/dashboard-overview.html"
      - title: Inizia con la dashboard Keystone
        url: "/integrations/dashboard-access.html"
      - title: Dashboard Keystone in BlueXP
        url: "/integrations/keystone-bluexp.html"
      - title: Dashboard Keystone in Digital Advisor
        url: "/integrations/keystone-aiq.html"
      - title: Cerca dati, genera report e visualizza avvisi
        url: "/integrations/options.html"
    - title: Visualizza informazioni sull'abbonamento
      entries:
      - title: Visualizza i dettagli del tuo abbonamento
        url: "/integrations/subscriptions-tab.html"
      - title: Visualizza i dettagli dei tuoi consumi attuali
        url: "/integrations/current-usage-tab.html"
      - title: Visualizza le tendenze di consumo
        url: "/integrations/consumption-tab.html"
      - title: Visualizza la cronologia del tuo abbonamento
        url: "/integrations/subscription-timeline.html"
    - title: Visualizza risorse
      entries:
      - title: Visualizza le risorse associate a un abbonamento
        url: "/integrations/assets-tab.html"
      - title: Visualizza le risorse su più abbonamenti
        url: "/integrations/assets.html"
    - title: Modifica i tuoi abbonamenti
      url: "/integrations/modify-subscription.html"
    - title: Visualizza la tua richiesta di servizio
      url: "/integrations/administration-tab.html"
    - title: Visualizza i dettagli dei volumi e dell'archiviazione degli oggetti
      url: "/integrations/volumes-objects-tab.html"
    - title: Visualizza le metriche delle performance
      url: "/integrations/performance-tab.html"
  - title: Concetti STaaS Keystone per v3
    entries:
    - title: Servizi Keystone STaaS
      entries:
      - title: Metriche e definizioni
        url: "/concepts/metrics.html"
      - title: Storage supportato
        url: "/concepts/supported-storage-services.html"
      - title: Capacità supportata
        url: "/concepts/supported-storage-capacity.html"
      - title: Livelli di servizio prestazionali
        url: "/concepts/service-levels.html"
      - title: Requisiti di capacità per i livelli di servizio prestazionali
        url: "/concepts/capacity-requirements.html"
    - title: Servizi add-on
      entries:
      - title: Protezione avanzata dei dati
        url: "/concepts/adp.html"
      - title: Opzioni di capacità di burst
        url: "/concepts/burst-capacity.html"
      - title: Informazioni sull'infrastruttura dati
        url: "/concepts/data-infra-insights.html"
      - title: Tiering dei dati
        url: "/concepts/data-tiering.html"
      - title: Componenti non restituibili, non volatili e conformità SnapLock
        url: "/concepts/nrnvc.html"
      - title: Supporto protetto USA (USPS)
        url: "/concepts/usps.html"
    - title: SLO Keystone STaaS
      entries:
      - title: Disponibilità
        url: "/concepts/sla-availability.html"
      - title: Performance
        url: "/concepts/sla-performance.html"
      - title: Sostenibilità
        url: "/concepts/sla-sustainability.html"
      - title: Garanzia di ripristino dal ransomware
        url: "/concepts/sla-ransomware.html"
    - title: Fatturazione
      entries:
      - title: Prezzo Keystone
        url: "/concepts/pricing.html"
      - title: Fatturazione basata sulla capacità impegnata
        url: "/concepts/committed-capacity-billing.html"
      - title: Misurazione basata sulla capacità consumata
        url: "/concepts/consumed-capacity-billing.html"
      - title: Fatturazione basata sul consumo burst
        url: "/concepts/burst-consumption-billing.html"
      - title: Scenari vari per la fatturazione Keystone
        url: "/concepts/misc-volume-billing.html"
      - title: Pianificazioni di fatturazione
        url: "/concepts/billing-schedules.html"
  - title: Concetti STaaS Keystone per v2
    entries:
    - title: Servizi Keystone STaaS
      entries:
      - title: Metriche e definizioni
        url: "/concepts/metrics-v2.html"
      - title: Qualità del servizio storage
        url: "/concepts/qos.html"
      - title: Storage supportato
        url: "/concepts/supported-storage-services-v2.html"
      - title: Capacità supportata
        url: "/concepts/supported-storage-capacity-v2.html"
      - title: Livelli di servizio prestazionali
        url: "/concepts/service-levels-v2.html"
      - title: Requisiti di capacità per i livelli di servizio prestazionali
        url: "/concepts/capacity-requirements-v2.html"
    - title: Servizi add-on
      entries:
      - title: Protezione avanzata dei dati
        url: "/concepts/adp-v2.html"
      - title: Informazioni sull'infrastruttura dati
        url: "/concepts/data-infra-insights-v2.html"
      - title: Tiering dei dati
        url: "/concepts/data-tiering-v2.html"
      - title: Componenti non restituibili, non volatili e conformità SnapLock
        url: "/concepts/nrnvc-v2.html"
      - title: Supporto protetto USA (USPS)
        url: "/concepts/usps-v2.html"
    - title: SLO Keystone STaaS
      entries:
      - title: Disponibilità
        url: "/concepts/sla-availability-v2.html"
      - title: Performance
        url: "/concepts/sla-performance-v2.html"
      - title: Sostenibilità
        url: "/concepts/sla-sustainability-v2.html"
      - title: Garanzia di ripristino dal ransomware
        url: "/concepts/sla-ransomware-v2.html"
    - title: Fatturazione
      entries:
      - title: Prezzo Keystone
        url: "/concepts/pricing-v2.html"
      - title: Fatturazione basata sulla capacità impegnata
        url: "/concepts/committed-capacity-billing-v2.html"
      - title: Misurazione basata sulla capacità consumata
        url: "/concepts/consumed-capacity-billing-v2.html"
      - title: Fatturazione basata sul consumo burst
        url: "/concepts/burst-consumption-billing-v2.html"
      - title: Scenari vari per la fatturazione Keystone
        url: "/concepts/misc-volume-billing-v2.html"
      - title: Pianificazioni di fatturazione
        url: "/concepts/billing-schedules-v2.html"
  - title: Accedi a Keystone dall'API REST di Digital Advisor
    entries:
    - title: Inizia a utilizzare l'API REST di Digital Advisor per recuperare i dati
        Keystone
      url: "/rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html"
    - title: Generare token di aggiornamento e accesso
      url: "/rest-api/generate-tokens.html"
    - title: Ottieni un elenco di tutti i clienti utilizzando l'API REST di Digital
        Advisor
      url: "/rest-api/get-customer-list.html"
    - title: Ottieni gli abbonamenti dei clienti utilizzando l'API REST di Digital
        Advisor
      url: "/rest-api/get-customer-subscriptions.html"
    - title: Ottieni dettagli sul consumo dei clienti utilizzando l'API REST di Digital
        Advisor
      url: "/rest-api/get-customer-consumption.html"
  - title: Keystone Subscription Services versione 1
    url: "/subscription-services-v1.html"
  - title: Ottieni aiuto con Keystone
    url: "/concepts/gssc.html"
  - title: Note legali
    url: "/legal-notices.html"
