---
sidebar: sidebar 
permalink: subscription-services-v1.html 
keywords: Keystone Flex Subscriptions, kfs v1, keystone legacy, Keystone subscription services version 1 
summary: Servizi di iscrizione Keystone STaaS su Keystone Flex 
---
= Servizi di iscrizione Keystone | versione 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone STaaS è stato preceduto da servizi di iscrizione Keystone (precedentemente noti come servizi di iscrizione Keystone Flex).

Mentre la navigazione delle due offerte è simile nellink:./integrations/keystone-console.html["Dashboard Keystone"^] I servizi di abbonamento Keystone differiscono da Keystone STaaS per quanto riguarda i livelli di servizio delle prestazioni costituenti, l'offerta di servizi e i principi di fatturazione. A partire da aprile 2024, NetApp gestisce e pubblica la documentazione solo per Keystone STaaS. Se stai ancora utilizzando i servizi di abbonamento Keystone , contatta il tuo KSM per ricevere supporto nella migrazione a Keystone STaaS. Se necessario, è possibile accedere alla versione PDF della documentazione sui servizi di abbonamento Keystone qui:

* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide.pdf["Inglese"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-ja-jp.pdf["Giapponese"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-ko-kr.pdf["Coreano"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-zh-cn.pdf["Cinese (semplificato)"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-zh-tw.pdf["Cinese (tradizionale)"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-de-de.pdf["Tedesco"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-es-es.pdf["Spagnolo"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-fr-fr.pdf["Francese"^]
* https://docs.netapp.com/a/keystone/1.0/keystone-subscription-services-guide-it-it.pdf["Italiano"^]

