---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp offre funzionalità nuove e migliorate in ogni release dei servizi Keystone STaaS. 
---
= Novità di Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le ultime funzionalità e i miglioramenti dei servizi Keystone STaaS.



== 10 novembre 2025

Nuovi miglioramenti nella dashboard Keystone nella NetApp Console:



=== Completa la casella di notifica della tua copertura

La scheda *Monitoraggio avvisi* nella pagina *Monitoraggio* include una casella di notifica *Completa la copertura* che appare quando ci sono lacune nella copertura.  In questa casella sono elencati gli abbonamenti per i quali mancano i monitor di capacità o scadenza e i monitor senza abbonamenti.  È possibile colmare le lacune aggiungendo abbonamenti ai monitor esistenti, creando nuovi monitor o eliminando quelli non utilizzati. Per saperne di più, fare riferimento a link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["Gestire le lacune di copertura per i monitor di allerta"].



== 13 ottobre 2025

Nuovi miglioramenti nella dashboard Keystone nella NetApp Console:



=== Colonna di override della policy QoS nella scheda Risorse

La scheda *Volumi nei cluster* all'interno della scheda *Risorse* ora include una colonna *Override policy QoS* che indica se le regole QoS vengono ignorate per i volumi di backup e mirror, visualizzando *true* (regole ignorate), *false* (regole applicate) o *N/D* (per i volumi mirror).


NOTE: Per gli abbonamenti Keystone v3, questa colonna visualizza *N/D* poiché i criteri QoS non sono applicabili nell'offerta v3.



=== Visibilità degli avvisi migliorata nella pagina Panoramica

La pagina *Panoramica* ora include due nuove sezioni di avviso denominate *Avvisi non risolti per gravità* e *Avvisi Keystone non risolti più vecchi*. Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["Dashboard Keystone nella console NetApp"] .



== 06 ottobre 2025



=== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e dei NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vederelink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione della console NetApp"^] .



== 22 settembre 2025



=== Aggiunta del monitoraggio degli avvisi

La dashboard Keystone in BlueXP ora include una scheda *Monitoraggio* per gestire avvisi e monitoraggi in tutti i tuoi abbonamenti.  Questa nuova scheda ti consente di:

* Visualizza e risolvi gli avvisi attivi, inclusi quelli generati dal sistema e definiti dall'utente, relativi all'utilizzo della capacità e alla scadenza dell'abbonamento.
* Crea monitor di avviso per monitorare l'utilizzo della capacità e gli eventi di scadenza degli abbonamenti.


Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alerts.html["Visualizza e gestisci avvisi e monitor"] .



=== Visualizzazione semplificata dei livelli di servizio delle prestazioni

È possibile visualizzare le informazioni sui livelli di servizio delle prestazioni, ora spostate da una scheda separata a una vista espandibile, all'interno della scheda *Abbonamenti*.  Fare clic sulla freccia rivolta verso il basso accanto alla colonna *Data di scadenza* per visualizzarle per ciascun abbonamento. Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/keystone-staas/integrations/subscriptions-tab.html["Visualizza i dettagli sui tuoi abbonamenti Keystone"] .



== 28 agosto 2025



=== Monitoraggio dell'utilizzo logico migliorato con una nuova colonna

È stata aggiunta una nuova colonna, Impronta totale, per migliorare il monitoraggio del consumo Keystone per i volumi FabricPool :

* * Dashboard Keystone in BlueXP*: puoi visualizzare la colonna *Impronta totale* nella scheda *Volumi nei cluster* all'interno della scheda *Risorse*.
* * Digital Advisor*: puoi visualizzare la colonna *Impronta totale* nella scheda *Dettagli volume* all'interno della scheda *Volumi e oggetti*.


Questa colonna visualizza l'ingombro logico totale per i volumi che utilizzano la suddivisione in livelli FabricPool , inclusi i dati provenienti sia dai livelli di prestazioni che da quelli di cold, in modo da poter calcolare con precisione il consumo Keystone .



== 05 agosto 2025



=== Visualizza i dati di consumo a livello di istanza

È possibile visualizzare i dati storici e di consumo correnti per ogni istanza del livello di servizio delle prestazioni tramite la dashboard Keystone in BlueXP. Questa funzionalità è disponibile per livelli di servizio di prestazioni con più istanze, a condizione che si disponga di un abbonamento Keystone versione 3 (v3). Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Visualizza il consumo dei tuoi abbonamenti Keystone"] .



== 30 giugno 2025



=== Rilascio Keystone versione 3 (v3).

Ora puoi abbonarti a Keystone versione 3 (v3), l'ultima release dell'offerta NetApp Keystone STaaS. Questa versione introduce diversi miglioramenti, tra cui livelli di servizio delle prestazioni semplificati, opzioni di capacità burst aggiuntive e frequenze di fatturazione flessibili. Questi miglioramenti semplificano la gestione, l'ottimizzazione e il ridimensionamento delle soluzioni di storage. Per saperne di più, fare riferimento alink:https://docs.netapp.com/us-en/keystone-staas/concepts/metrics.html["Servizi Keystone STaaS per v3"] .

Puoi contattare il team di supporto Keystone per abbonarti alla versione 3 (v3) Keystone . Per maggiori dettagli, fare riferimento a link:https://docs.netapp.com/us-en/keystone-staas/concepts/support-services.html["Ottieni aiuto con Keystone"].



== 19 giugno 2025



=== Dashboard Keystone in BlueXP

Ora puoi accedere alla dashboard di Keystone direttamente da BlueXP. Questa integrazione ti offre un unico punto di monitoraggio, gestione e tracciamento di tutti i tuoi abbonamenti Keystone e degli altri servizi NetApp.

Con la dashboard Keystone in BlueXP puoi:

* Visualizza tutti i dettagli del tuo abbonamento, l'utilizzo della capacità e le risorse in un unico posto.
* Gestisci facilmente gli abbonamenti e richiedi modifiche in base all'evoluzione delle tue esigenze.
* Rimani aggiornato sulle ultime informazioni relative al tuo ambiente di archiviazione.


Per iniziare, vai su *Archiviazione > Keystone* nel menu di navigazione a sinistra di BlueXP. Per ulteriori informazioni, fare riferimento a link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Panoramica della dashboard Keystone"].



== 08 gennaio 2025



=== Aggiunta di opzioni di visualizzazione dell'utilizzo giornaliero dei dati

È ora possibile visualizzare l'utilizzo dei dati burst maturati giornalmente in formato grafico o tabella per un periodo di fatturazione mensile o trimestrale facendo clic sulla barra che visualizza i dati fatturati. Per ulteriori informazioni, fare riferimento a link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["Visualizza l'utilizzo giornaliero dei dati burst maturati"].



== 12 dicembre 2024



=== Rinominata colonna logica utilizzata

La colonna *logica utilizzata* nella scheda *Dettagli volume* all'interno di *volumi e oggetti* è ora rinominata *Keystone Logical used*.



=== Scheda risorse avanzate

La scheda *risorse* nella schermata *Sottoscrizioni Keystone* contiene ora due nuove sotto-schede: *ONTAP* e *StorageGRID*. Queste sotto-schede offrono informazioni dettagliate a livello del cluster per ONTAP e informazioni a livello di grid per StorageGRID in base alle tue iscrizioni. Per ulteriori informazioni, fare riferimento a link:./integrations/assets-tab.html["Scheda risorse"^].



=== Nuova opzione Nascondi/Mostra colonne

La scheda *Dettagli volume* all'interno di *volumi e oggetti* include ora l'opzione *Nascondi/Mostra colonne*. Questa opzione consente di selezionare o deselezionare le colonne per personalizzare l'elenco tabulare dei volumi in base alle proprie preferenze. Per ulteriori informazioni, fare riferimento a link:./integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



== 21 novembre 2024



=== Burst maturato fatturato migliorato

È ora possibile visualizzare i dati sull'utilizzo del bursting maturato su base trimestrale tramite l'opzione *Burst maturato fatturato* se si è scelto un periodo di fatturazione trimestrale. Per ulteriori informazioni, fare riferimento a link:./integrations/consumption-tab.html#view-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Nuove colonne nella scheda Dettagli volumi

Per migliorare la chiarezza nel calcolo dell'utilizzo logico, sono state aggiunte due nuove colonne alla scheda *Dettagli volume* nella scheda *volumi e oggetti*:

* *AFS logico*: Visualizza la capacità logica utilizzata dal file system attivo del volume.
* *Istantanea fisica*: Visualizza lo spazio fisico utilizzato dagli snapshot.


Queste colonne forniscono una maggiore chiarezza nella colonna *logica utilizzata*, che mostra la capacità logica combinata utilizzata dal file system attivo del volume e lo spazio fisico utilizzato dagli snapshot.



== 11 novembre 2024



=== Generazione di rapporti migliorata

Ora puoi generare un report consolidato per visualizzare i dettagli dei tuoi dati Keystone utilizzando la funzionalità Report in Digital Advisor. Per saperne di più, fare riferimento a link:./integrations/options.html#generate-consolidated-report-from-digital-advisor["Generare un rapporto consolidato"^] .



== 10 luglio 2024



=== Modifiche alle etichette

L'etichetta *uso corrente* viene modificata in *consumo corrente* e *tendenza capacità* viene modificata in *tendenza consumo*.



=== Barra di ricerca per gli abbonamenti

Il menu a discesa *Sottoscrizioni* in tutte le schede della schermata *Sottoscrizioni Keystone* include ora una barra di ricerca. È possibile cercare sottoscrizioni specifiche elencate nel menu a discesa *Sottoscrizioni*.



== 27 giugno 2024



=== Visualizzazione coerente dell'abbonamento

La schermata *Iscrizioni Keystone* viene aggiornata per visualizzare il numero di abbonamento selezionato in tutte le schede.

* Quando viene aggiornata una scheda nella schermata *Sottoscrizioni Keystone*, la schermata passa automaticamente alla scheda *Sottoscrizioni* e ripristina tutte le schede alla prima sottoscrizione elencata nel menu a discesa *sottoscrizione*.
* Se l'abbonamento selezionato non è iscritto alle metriche di prestazione, la scheda *prestazioni* visualizzerà il primo abbonamento elencato nel menu a discesa *abbonamento* al momento della navigazione.




== 29 maggio 2024



=== Indicatore burst migliorato

L'indicatore *Burst* nell'indice grafico di utilizzo è stato migliorato per visualizzare il valore percentuale del limite burst. Questo valore cambia a seconda del limite di burst concordato per un abbonamento. È inoltre possibile visualizzare il valore del limite di burst nella scheda *Sottoscrizioni* passando con il mouse sull'indicatore *utilizzo burst* nella colonna *Stato utilizzo*.



=== Aggiunta di livelli di servizio

I livelli di servizio *CVO primario* e *CVO secondario* sono inclusi per supportare Cloud Volumes ONTAP per gli abbonamenti che hanno piani tariffari con zero capacità impegnata o quelli configurati con un cluster metro.

* È possibile visualizzare il grafico dell'utilizzo della capacità per questi livelli di servizio dal vecchio dashboard del widget *Keystone Subscription* e dalla scheda *Capacity Trend*, nonché informazioni dettagliate sull'utilizzo dalla scheda *utilizzo corrente*.
* Nella scheda *Sottoscrizioni*, questi livelli di servizio vengono visualizzati come `CVO (v2)` Nella colonna *tipo di utilizzo*, che consente l'identificazione della fatturazione in base a questi livelli di servizio.




=== Funzione di ingrandimento per burst a breve termine

La scheda *Trend capacità* include ora una funzione di zoom per visualizzare i dettagli delle sequenze di burst a breve termine nei grafici di utilizzo. Per ulteriori informazioni, vedere link:./integrations/consumption-tab.html["Scheda Trend capacità"^].



=== Visualizzazione migliorata degli abbonamenti

La visualizzazione predefinita delle sottoscrizioni è stata migliorata per ordinare in base all'ID di rilevamento. Le sottoscrizioni nella scheda *Sottoscrizioni*, inclusi i rapporti a discesa *sottoscrizione* e CSV, verranno ora visualizzate in base alla sequenza alfabetica degli ID di tracciamento, seguendo l'ordine di a, A, b, B e così via.



=== Display burst migliorato

La descrizione comandi visualizzata quando si passa il mouse sul grafico a barre dell'utilizzo della capacità nella scheda *tendenza capacità* visualizza ora il tipo di burst maturato in base alla capacità impegnata. Esso differenzia tra burst accantonato provvisorio e fatturato, indicando *consumo accantonato provvisorio* e *consumo maturato fatturato* per abbonamenti con piani tasso di capacità impegnati zero, e *Burst accantonato provvisorio* e *Burst maturato fatturato* per quelli con capacità impegnata diversa da zero.



== 09 maggio 2024



=== Nuove colonne nei rapporti CSV

I report CSV della scheda *tendenza capacità* includono ora le colonne *numero di abbonamento* e *Nome account* per migliorare i dettagli.



=== Colonna tipo di utilizzo avanzato

La colonna *tipo di utilizzo* all'interno della scheda *Sottoscrizioni* è stata migliorata per visualizzare gli utilizzi logici e fisici come valori separati da virgole per le sottoscrizioni che coprono i livelli di servizio sia per i file che per gli oggetti.



=== Accedi ai dettagli dello storage a oggetti dalla scheda Dettagli del volume

La scheda *Dettagli volume* all'interno della scheda *volumi e oggetti* fornisce ora dettagli sull'archiviazione degli oggetti insieme alle informazioni sul volume per le sottoscrizioni che includono livelli di servizio sia per i file che per gli oggetti. È possibile fare clic sul pulsante *Dettagli archiviazione oggetti* nella scheda *Dettagli volume* per visualizzare i dettagli.



== 28 marzo 2024



=== Miglioramento della conformità alle policy QoS nella scheda Volume Details (Dettagli volume)

La scheda *Dettagli volume* all'interno della scheda *volumi e oggetti* offre ora una migliore visibilità della conformità alle policy QoS (Quality of Service). La colonna precedentemente nota come *AQoS* viene rinominata *conforme*, che indica se il criterio QoS è conforme. Inoltre, viene aggiunta una nuova colonna *tipo di criterio QoS*, che specifica se il criterio è fisso o adattivo. Se non è applicabile, la colonna visualizza _non disponibile_. Per ulteriori informazioni, vedere link:./integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Nella scheda Volume Summary (Riepilogo volume) vengono visualizzate una nuova colonna e una sottoscrizione semplificata

* La scheda *Volume Summary* nella scheda *Volumes & Objects* include ora una nuova colonna denominata *Protected*. Questa colonna fornisce un conteggio dei volumi protetti associati ai livelli di servizio sottoscritti. Se si fa clic sul numero di volumi protetti, viene visualizzata la scheda *Dettagli volume*, in cui è possibile visualizzare un elenco filtrato di volumi protetti.
* La scheda *Riepilogo volume* viene aggiornata per visualizzare solo le sottoscrizioni di base, esclusi i servizi aggiuntivi. Per ulteriori informazioni, vedere link:./integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].




=== Passare alla visualizzazione dei dettagli del burst maturato nella scheda Trend capacità

La descrizione comandi visualizzata quando si passa il mouse sul grafico a barre dell'utilizzo della capacità nella scheda *tendenza capacità* visualizza i dettagli dei burst maturati per il mese corrente. I dettagli non saranno disponibili per i mesi precedenti.



=== Accesso migliorato per visualizzare i dati storici per le iscrizioni a Keystone

Ora puoi visualizzare i dati storici se un abbonamento Keystone viene modificato o rinnovato. È possibile impostare la data di inizio di un abbonamento a una data precedente per visualizzare :

* Dati sui consumi e sull'utilizzo a raffica accumulato dalla scheda *Tendenze capacità*.
* Metriche delle prestazioni dei volumi ONTAP dalla scheda *Prestazioni*.


I dati vengono visualizzati in base alla data di inizio selezionata per l'abbonamento.



== 29 febbraio 2024



=== Aggiunta della scheda risorse

La schermata *Iscrizioni Keystone* ora include la scheda *risorse*. Questa nuova scheda fornisce informazioni a livello del cluster in base alle iscrizioni. Per ulteriori informazioni, vedere link:./integrations/assets-tab.html["Scheda risorse"^].



=== Miglioramenti alla scheda volumi e oggetti

Per una maggiore chiarezza dei volumi del sistema ONTAP, nella scheda *volumi* sono stati aggiunti due nuovi pulsanti di tabulazione, *Riepilogo volume* e *Dettagli volume*. La scheda *Volume Summary* fornisce un conteggio complessivo dei volumi associati ai livelli di servizio sottoscritti, incluse le informazioni sullo stato di conformità AQoS e sulla capacità. La scheda *Dettagli volume* elenca tutti i volumi e le relative specifiche. Per ulteriori informazioni, vedere link:./integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Migliore esperienza di ricerca su Digital Advisor

I parametri di ricerca nella schermata *Digital Advisor* ora includono i numeri di iscrizione Keystone e le liste di controllo create per le iscrizioni Keystone. È possibile immettere i primi tre caratteri del numero di abbonamento o del nome della lista di controllo. Per ulteriori informazioni, vedere link:./integrations/keystone-aiq.html["Visualizza la dashboard Keystone su Active IQ Digital Advisor"^].



=== Visualizzare la data e l'ora dei dati di consumo

È possibile visualizzare la data e l'ora dei dati di consumo (in UTC) sul vecchio dashboard del widget *Keystone Subscriptions*.



== 13 febbraio 2024



=== Possibilità di visualizzare gli abbonamenti collegati a un abbonamento principale

Alcuni abbonamenti primari possono avere abbonamenti secondari collegati. In questo caso, il numero di abbonamento principale continuerà a essere visualizzato nella colonna *numero di abbonamento*, mentre i numeri di abbonamento collegati saranno elencati in una nuova colonna *Sottoscrizioni collegate* nella scheda *Sottoscrizioni*. La colonna *Sottoscrizioni collegate* diventa disponibile solo se si dispone di sottoscrizioni collegate ed è possibile visualizzare messaggi informativi che ne informano l'utente.



== 11 gennaio 2024



=== Dati fatturati restituiti per il burst maturato

Le etichette per *Burst maturato* sono ora modificate in *Burst maturato fatturato* nella scheda *Trend capacità*. Selezionando questa opzione è possibile visualizzare i grafici mensili per i dati burst maturati fatturati. Per ulteriori informazioni, vedere link:./integrations/consumption-tab.html#view-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Dettagli sui consumi maturati per piani tariffari specifici

Se si dispone di un abbonamento con piani tariffari con capacità impegnata _zero_, è possibile visualizzare i dettagli sui consumi maturati nella scheda *tendenza capacità*. Selezionando l'opzione *consumo maturato fatturato*, è possibile visualizzare i grafici mensili per i dati di consumo maturato fatturato.



== 15 dicembre 2023



=== Possibilità di effettuare ricerche in base alle liste di controllo

Il supporto per le liste di controllo in Digital Advisor è stato esteso per includere i sistemi Keystone. È ora possibile visualizzare i dettagli degli abbonamenti per più clienti effettuando una ricerca con gli elenchi di controllo. Per ulteriori informazioni sull'utilizzo delle liste di controllo in Keystone STaaS, vedere link:./integrations/keystone-aiq.html#search-by-keystone-watchlists["Ricerca per elenchi di controllo Keystone"^].



=== Data di conversione in fuso orario UTC

I dati restituiti nelle schede della schermata *Abbonamenti Keystone* di Digital Advisor vengono visualizzati in base all'ora UTC (fuso orario del server). Quando si immette una data per la query, questa viene automaticamente considerata nel fuso orario UTC. Per ulteriori informazioni, vedere link:./integrations/keystone-aiq.html["Dashboard e reporting per l'abbonamento Keystone"^].
