---
sidebar: sidebar 
permalink: rest-api/get-customer-consumption.html 
keywords: api, consumption, subscriptions, customerID, keystone, Digital Advisor 
summary: 'L"API REST di Digital Advisor recupera i dettagli di consumo correnti per tutti gli abbonamenti associati con l"ID cliente specificato.' 
---
= Ottieni i dettagli sui consumi dei clienti Keystone utilizzando l'API REST Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa API recupera i dettagli di consumo correnti per tutte le sottoscrizioni associate con l'ID cliente specificato.

*Richiesta:*

[cols="24%,76%"]
|===


| *Metodo* | OTTIENI 


| *Endpoint* | `https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details` 


| *Parametri*  a| 
* tipo: "cliente"
* id: <customer-id>




| *Intestazioni*  a| 
* accetta: applicazione/json
* AuthorizationToken: <access_key>


|===
*Risposta:* l'API risponderà con un oggetto JSON contenente un elenco di tutte le sottoscrizioni con le metriche di utilizzo del servizio correnti per il cliente specificato. Ecco un esempio di risposta:

[listing]
----
{
"result":  {
"returned_records": "string",
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "string",
"end_date": "string"
},
"service_levels": [
{
"name": "string",
"committed_tib": "string",
"consumed_tib": "string",
"consumed_timestamp_utc": "string",
"burst_tib": "string",
"accrued_burst_tib": "string"
}
]
}
],
"request_id": "string",
"response_time": "string"
}
}
----
*Codice di stato*: 200 – richiesta riuscita

*Esempio Curl*:

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq.netapp.com/v1/keystone/customer/consumption-details?type=customer&id=<customerID>' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----


== Ottenere i dettagli di consumo cronologici per un cliente

Questa API recupera i dettagli del consumo cronologico per tutte le sottoscrizioni associate all'ID cliente specificato in base all'intervallo di tempo specificato.

*Richiesta:*

[cols="24%,76%"]
|===


| *Metodo* | OTTIENI 


| *Endpoint* | `https://api.activeiq.netapp.com/v1/keystone/customer/historical-consumption-details` 


| *Parametri*  a| 
* tipo: "cliente"
* id: <customer-id>
* From_date_utc: <data di inizio (nel formato RFC3339)>
* To_date_utc: <data di fine (nel formato RFC3339)>




| *Intestazioni*  a| 
* accetta: applicazione/json
* AuthorizationToken: <access_key>


|===
*Risposta:*

L'API risponderà con un oggetto JSON contenente un elenco di tutti gli abbonamenti con le metriche di utilizzo cronologico del servizio per il cliente specificato nell'intervallo di tempo selezionato. Ecco un esempio di risposta:

[listing]
----
{
"results":  {
"returned_records": 0,
"records": [
{
"subscription":  {
"account_name": "string",
"number": "string",
"start_date": "2023-08-24T14:15:22Z",
"end_date": "2023-08-24T14:15:22Z"
},
"service_levels": [
{
"name": "string",
"historical_consumption": [
{
"committed_tib": 0,
"consumed_tib": 0,
"timestamp_utc": "2023-08-24T14:15:22Z",
"burst_tib": 0,
"accrued_burst_tib": 0,
"is_invoiced": true
}
]
}
]
}
],
"request_parameters":  {
"from_date_utc": "2023-08-24",
"to_date_utc": "2023-08-24",
"customer_id": "string"
},
"request_id": "string",
"response_time": "string",
"customer":  {
"name": "string",
"id": "string"
}
}
}
----
*Codice di stato*: 200 – richiesta riuscita

*Esempio Curl*:

[source, curl]
----
curl -X 'GET' \ 'https://api.activeiq-stg.netapp.com/v1/keystone/customer/historical-consumption-details? type=customer&id=<customerID>&from_date_utc=2023-08-24T14%3A15%3A22Z&t _date_utc=2023-08-24T14%3A15%3A22Z' \ -H 'accept: application/json' \ -H 'authorizationToken: <access-key>'
----