= Nuove colonne nella scheda Volumes in clusters
:allow-uri-read: 


Nuovi miglioramenti nella dashboard Keystone nella NetApp Console:



[[new-columns-in-the-volumes-in-clusters-tab]]
=== Nuove colonne nella scheda Volumes in clusters

Tre nuove colonne, *Dati caldi*, *Livello freddo (%)* e *Livello caldo (%)*, sono state aggiunte alla scheda *Volumi nei cluster* in *Assets*. Per saperne di più, consulta  https://docs.netapp.com/us-en/keystone-staas/integrations/assets-tab.html["Visualizza le risorse associate a un abbonamento Keystone"] e  https://docs.netapp.com/us-en/keystone-staas/integrations/assets.html["Visualizza le risorse nei tuoi abbonamenti Keystone"].



[[invoiced-uninvoiced-and-provisional-burst-usage-in-consumption-trend]]
=== Utilizzo fatturato, non fatturato e burst provvisorio in Consumption trend

Il grafico della fatturazione dei consumi a raffica accumulati nella scheda *Andamento dei consumi* ora mostra i consumi fatturati, non fatturati e provvisori. Per ulteriori informazioni, consultare https://docs.netapp.com/us-en/keystone-staas/integrations/consumption-tab.html#view-accrued-burst["Visualizza il burst accumulato"].



[[enhancements-to-the-monitoring-view]]
=== Miglioramenti alla vista Monitoring

La vista *Monitoring* include i seguenti aggiornamenti:

* *Scheda Alerts*: la colonna *Alert* è stata rinominata *Alert type & condition*. Ora puoi anche utilizzare l'icona con i puntini di sospensione accanto alla colonna *Status* per modificare un alert, aggiungere una nota o visualizzare i dettagli dell'alert.
* *Scheda Monitor avvisi*: la colonna *Condizione* è stata rinominata *Tipo di monitor e condizione*.


Per saperne di più, consulta  https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alerts.html["Visualizza e gestisci gli avvisi per gli abbonamenti Keystone"] e  https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html["Visualizza e crea monitor di avviso per gli abbonamenti Keystone"].
