---
sidebar: sidebar 
permalink: concepts/burst-consumption-billing.html 
keywords: burst consumption billing 
summary: La fatturazione Keystone STaaS si basa sulla capacità di picco, ovvero la capacità consumata da te, oltre alla capacità impegnata della tua iscrizione. 
---
= Comprendere la fatturazione dei consumi a raffica Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La fatturazione di Keystone STaaS si basa sulla _capacità di burst_, ovvero la capacità consumata da te, oltre alla capacità impegnata della tua iscrizione.

Il limite di burst viene determinato e specificato nel contratto Keystone. Per impostazione predefinita, è impostato al 20% in più rispetto alla capacità impegnata. È anche possibile scegliere limiti di capacità massima del 40% o del 60% della capacità impegnata. Per ulteriori informazioni, fare riferimento a link:../concepts/burst-capacity.html["Opzioni di aumento della capacità di burst"].

La capacità impegnata è la capacità che ti viene dedicata durante l'acquisto dell'abbonamento. La capacità impegnata e la capacità di picco vengono misurate in base al livello di servizio delle prestazioni. La capacità consumata è la capacità effettivamente utilizzata dai carichi di lavoro.

Quando la capacità consumata è maggiore della capacità impegnata per un livello di servizio prestazionale, il consumo a raffica viene registrato e addebitato di conseguenza. L'utilizzo al di sopra della capacità di burst viene indicato come "al di sopra del limite di burst".

Questo processo si verifica per ogni record di consumo generato. Il consumo di burst, pertanto, riflette sia la quantità che la durata delle capacità di consumo eccessivo in aggiunta alle capacità impegnate. Per ulteriori informazioni, fare riferimento a link:../integrations/consumption-tab.html["Visualizza i trend di consumo dei tuoi abbonamenti Keystone"].

Per informazioni sulle diverse capacità supportate in Keystone, vedere link:../concepts/supported-storage-capacity.html["Capacità di storage supportate in Keystone"].
