---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Il servizio add-on di tiering dei dati identifica i dati utilizzati meno di frequente ed esegue il tiering dei dati nello storage supportato. 
---
= Servizio aggiuntivo di tiering dei dati per Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I servizi standard Keystone STaaS per file e storage a blocchi includono funzionalità di tiering che identificano i dati utilizzati meno frequentemente e li spostano nello storage a freddo NetApp supportato da Keystone STaaS. È possibile utilizzare il tiering dei dati come servizio aggiuntivo se si desidera spostare i dati a freddo in qualsiasi storage supportato da Keystone STaaS, non-NetApp. Questo servizio aggiuntivo è supportato solo sul tipo di storage dati unificato.

vedere link:../concepts/service-levels.html["Livelli di servizio prestazionali a Keystone"] .


NOTE: Il servizio aggiuntivo di tiering è necessario solo quando i dati vengono suddivisi in livelli verso qualsiasi storage non-NetApp, come Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) e altri storage a oggetti di terze parti compatibili S3 supportati da Keystone STaaS. Questo servizio è disponibile solo per il tipo di storage dati unificato.

La funzionalità di tiering sfrutta la tecnologia NetApp FabricPool che consente il tiering automatizzato dei dati con accesso non frequente ai Tier di storage a oggetti on-premise e off-premise.

Il servizio aggiuntivo di suddivisione in livelli dei dati consente la suddivisione in livelli da Extreme, Premium, Performance, Standard e Value a una destinazione di archiviazione di oggetti. Il rapporto tra dati attivi e dati passivi da suddividere in livelli non è fisso e ogni livello viene misurato e fatturato separatamente.

Ad esempio, se la destinazione per il Tier di cold storage è:

* Livello Keystone STaaS Value, livello Keystone STaaS StorageGRID Object o griglia StorageGRID Webscale (SGWS) esistente (di proprietà del cliente): non sono previsti costi aggiuntivi; fa parte del servizio standard.
* Cloud pubblico (AWS, Azure, Google) o storage a oggetti di terze parti supportato da Keystone STaaS - è previsto un costo aggiuntivo per la capacità dei dati che viene tierata verso il target del cold storage.


I costi per i servizi aggiuntivi di tiering si applicano per l'intera durata dell'abbonamento.


NOTE: I servizi di elaborazione, archiviazione e rete basati su hyperscaler richiesti da Cloud Volumes ONTAP non sono forniti da NetApp come parte degli abbonamenti Keystone STaaS; questi servizi devono essere acquistati direttamente dai provider di servizi cloud hyperscaler.

*Informazioni correlate*

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["Come approssimare il consumo di Keystone con il tiering dei dati (FabricPool) utilizzando l'interfaccia a riga di comando di ONTAP"^]
