---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: Il servizio add-on di tiering dei dati identifica i dati utilizzati meno di frequente ed esegue il tiering dei dati nello storage supportato. 
---
= Scopri di più sul tiering dei dati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I servizi standard di Keystone STaaS per lo storage a blocchi e file includono funzionalità di tiering che identificano i dati utilizzati con minore frequenza e lo Tier allo storage a freddo NetApp supportato da Keystone STaaS. Puoi utilizzare il tiering dei dati come servizio add-on per eseguire il tiering dei dati cold su qualsiasi storage non NetApp supportato da Keystone STaaS.

Per informazioni sui servizi standard e aggiuntivi, vedere link:../concepts/supported-storage-services.html["Servizi Keystone STaaS"]. Per informazioni sui livelli di servizio, vedere link:../concepts/service-levels.html["Livelli di servizio in Keystone"].

Il servizio tiering add-on è necessario solo quando i dati sono sottoposti a tiering in qualsiasi storage non NetApp come Amazon Web Services (AWS) S3, BLOB di Azure, Google Cloud Platform (GCP) e altro, storage a oggetti di terze parti compatibile con Keystone STaaS e supportato da S3.

La funzionalità di tiering sfrutta la tecnologia NetApp FabricPool che consente il tiering automatizzato dei dati con accesso non frequente ai Tier di storage a oggetti on-premise e off-premise.

Il servizio di tiering dei dati add-on consente il tiering da Extreme, Premium, Performance, Standard e Value Tier a una destinazione di storage a oggetti. Il rapporto tra dati hot e dati cold da Tier non è fisso e ogni Tier viene misurato e fatturato separatamente.

Ad esempio, se la destinazione per il Tier di cold storage è:

* Keystone STaaS Value Tier, Keystone STaaS StorageGRID Object Tier o griglia SGWS esistente (di proprietà del cliente) - non sono previsti costi aggiuntivi; fa parte del servizio standard.
* Cloud pubblico (AWS, Azure, Google) o storage a oggetti di terze parti supportato da Keystone STaaS - è previsto un costo aggiuntivo per la capacità dei dati che viene tierata verso il target del cold storage.


I costi per i servizi aggiuntivi di tiering si applicano per l'intera durata dell'abbonamento.


NOTE: I servizi di calcolo, storage e rete basati su hyperscalar richiesti da Cloud Volumes ONTAP non sono forniti da NetApp come parte degli abbonamenti STaaS Keystone; questi servizi devono essere acquistati direttamente dai provider di servizi cloud hyperscalar.

*Informazioni correlate*

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["Come approssimare il consumo di Keystone con il tiering dei dati (FabricPool) utilizzando l'interfaccia a riga di comando di ONTAP"^]
