---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Global Services Support Center, GSSC, Keystone support, service request, support ticket 
summary: NetApp Global Services Support Center GSSC 
---
= NetApp Global Services Support Center
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il centro di assistenza e servizi globali NetApp (GSSC) e il responsabile del successo NetApp Keystone (KSM) sono responsabili della fornitura dei servizi per gli abbonamenti Keystone.



== NetApp Global Services and Support Center (GSSC)

NetApp fornisce servizi operativi in remoto ai clienti NetApp Keystone. Questi servizi comprendono una gamma di discipline operative per le attività di gestione dello storage. Questi servizi includono gestione delle risorse e della configurazione, gestione della capacità e delle performance, gestione delle modifiche, gestione di eventi, incidenti e problemi, evasione delle richieste di servizio e reporting. NetApp dimostra lo stato di controllo e le prove di supporto necessarie.



== Informazioni aggiuntive e contatto per il supporto

Il team dei servizi e supporto globali NetApp (GSSC) supporta principalmente i servizi ai clienti NetApp Keystone. Puoi utilizzare le seguenti informazioni per contattare il team di supporto.

* Contatti per il servizio globale:https://www.netapp.com/us/contact-us/support.aspx[]
* Se si dispone di un caso/ticket aperto che deve essere sottoposto a escalation, inviare un'e-mail a uno dei seguenti indirizzi: keystone.services@netapp.com keystone.escalations@netapp.com
* NetApp utilizza la soluzione AIOPS per monitorare e connettersi in modo proattivo all'ambiente NetApp Keystone per la risoluzione dei problemi.



NOTE: In un modello gestito dal partner, le richieste di servizio del tenant e del subtenant vengono assegnate al service desk del partner. Il tool di supporto del partner potrebbe essere integrato con la soluzione AIOPS e le applicazioni GSSC. Solo i problemi L3 vengono inoltrati a NetApp tramite GSSC.

Per ulteriori informazioni sui servizi Keystone, consulta:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentazione sui prodotti NetApphttps://docs.netapp.com["https://docs.netapp.com"^]




== Monitoraggio GSSC

NetApp Global Services and Support Center (GSSC) monitora lo stato dei prodotti e dei servizi sottoscritti, fornisce supporto remoto e collabora con Keystone Success Manager. Tutto il personale che monitora i prodotti associati ai relativi ordini di abbonamento Keystone è cittadino statunitense che opera negli Stati Uniti suolo.

.Keystone Success Manager
Keystone Success Manager (KSM) lavora a stretto contatto con te sui servizi Keystone e ti aggiorna sui report operativi e di fatturazione settimanali o mensili. Le responsabilità sono specificate nel contratto NetApp Keystone.



== Generazione di richieste di servizio

Durante l'assunzione, se hai fornito le credenziali per accedere e utilizzare NetApp Keystone ServiceNow, puoi utilizzare il portale per generare richieste di servizio per problemi relativi alle tue sottoscrizioni Keystone:

https://netappgssc.service-now.com/csm[]

Prima di inviare la richiesta di servizio, assicurarsi di disporre dei dettagli di sistema, dei registri e delle informazioni correlate. Quando si solleva una richiesta di servizio, il team GSSC riceve il ticket di supporto e accede alle informazioni per la risoluzione dei problemi. Puoi seguire il tuo ticket ServiceNow per conoscere lo stato e la risoluzione.

Per informazioni sull'aggiunta di pacchetti di supporto, vedere link:../installation/monitor-health.html["Generare e raccogliere bundle di supporto"].
