---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Keystone support, service request, support ticket 
summary: Per assistenza, contattare il Centro assistenza e servizi globali NetApp. 
---
= Ottieni aiuto con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il team di supporto NetApp Keystone e il Keystone Success Manager (KSM) forniscono la tua assistenza per le tue iscrizioni a Keystone. Se hai bisogno di aiuto, puoi contattare il team di supporto Keystone.



== Supporto NetApp Keystone

NetApp fornisce servizi operativi in remoto ai clienti NetApp Keystone. Questi servizi comprendono una gamma di discipline operative per le attività di gestione dello storage. Questi servizi includono gestione delle risorse e della configurazione, gestione della capacità e delle performance, gestione delle modifiche, gestione di eventi, incidenti e problemi, evasione delle richieste di servizio e reporting. NetApp dimostra uno stato di controllo e prove a sostegno, come richiesto.



== Ulteriori informazioni

NetApp utilizza la soluzione di monitoraggio ITOM per monitorare e connettersi in modo proattivo all'ambiente NetApp Keystone per la risoluzione dei problemi.


NOTE: In un modello gestito dal partner, le richieste di servizio del tenant e del subtenant vengono assegnate al service desk del partner. Lo strumento di supporto del partner potrebbe essere integrato con la soluzione ITOM.

Per ulteriori informazioni sui servizi Keystone, consulta:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentazione sui prodotti NetApphttps://docs.netapp.com["https://docs.netapp.com"^]




== Monitoring del supporto Keystone

Il supporto NetApp Keystone monitora la salute dei tuoi prodotti e dei servizi a cui ti sei abbonato, offre supporto da remoto e collabora con il tuo Keystone Success Manager.

.Keystone Success Manager
Il Keystone Success Manager (KSM) lavora a stretto contatto con te sui tuoi servizi Keystone e ti aggiorna in merito alla fatturazione settimanale o mensile e ai report operativi. Le responsabilità sono specificate nel contratto NetApp Keystone.



== Generazione di richieste di servizio

Durante l'assunzione, se hai fornito le credenziali per accedere e utilizzare NetApp Keystone ServiceNow, puoi utilizzare il portale per generare richieste di servizio per problemi relativi alle tue sottoscrizioni Keystone:

https://netappgssc.service-now.com/csm[]

Prima di inviare la richiesta di servizio, assicurarsi di disporre dei dettagli di sistema, dei registri e delle informazioni correlate. Quando rilanci una richiesta di servizio, il team di supporto Keystone riceve il ticket di supporto e accede alle informazioni per il troubleshooting. Puoi seguire il tuo ticket ServiceNow per conoscere lo stato e la risoluzione.

Per informazioni sull'aggiunta di pacchetti di supporto, vedere link:../installation/monitor-health.html["Generare e raccogliere bundle di supporto"].

Se si dispone di un caso/ticket aperto che deve essere sottoposto a escalation, inviare un'e-mail a uno dei seguenti indirizzi: keystone.services@netapp.com keystone.escalations@netapp.com
