---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Keystone billing, special volume types, cloned volumes, SnapMirror destinations, LUNs, temporary volumes 
summary: Le regole di fatturazione di Keystone variano a seconda della configurazione del volume. Questa pagina illustra la fatturazione per volumi clonati, SnapMirror destinazioni, LUN, volumi temporanei e volumi di sistema. 
---
= Fatturazione Keystone per tipologie di volume specifiche
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le regole di fatturazione di Keystone variano a seconda della configurazione del volume. Conoscere queste eccezioni consente di evitare addebiti imprevisti quando si lavora con volumi clonati, destinazioni SnapMirror, LUN o storage temporaneo.

La tabella seguente riassume le regole di fatturazione per ciascun tipo di volume.

[cols="1,2"]
|===
| Tipo di volume | Regola di fatturazione 


| Volumi clonati | Fatturati secondo i volumi standard 


| Volumi temporanei | Non fatturato 


| SnapMirror destinazioni | Fatturato in base al livello di servizio di prestazione della destinazione 


| LUN | Fatturato in base al livello di servizio prestazionale del volume di riferimento 


| Volumi di sistema e root | Monitorato ma non fatturato 
|===


== Fatturazione per volumi clonati

I volumi clonati vengono fatturati come volumi standard allo stesso livello di servizio prestazionale del volume da cui sono stati clonati. Tutti i volumi clonati vengono misurati e fatturati indipendentemente dalle loro dimensioni o finalità.



== Fatturazione per volumi temporanei

Occasionalmente, i volumi temporanei (TMP) vengono creati da ONTAP durante lo spostamento dei volumi. Questi volumi temporanei sono di breve durata e il consumo su questi volumi non viene misurato per la fatturazione.



== Fatturazione per destinazioni SnapMirror

Il prezzo dei volumi di destinazione SnapMirror, sia per il disaster recovery che per la conservazione a lungo termine, si basa sul livello di servizio prestazionale assegnato alla destinazione. Non sono previsti costi aggiuntivi per la protezione dei dati.



== Fatturazione per LUN

Per le LUN, la fatturazione si basa sui livelli di servizio delle prestazioni del volume.



== Volumi di sistema e root

I volumi di sistema e root vengono monitorati come parte del monitoraggio generale del servizio Keystone, ma non vengono conteggiati o fatturati. Il consumo su questi volumi è esentato per la fatturazione.
