---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Scopri la fatturazione di Keystone per configurazioni specifiche, tra cui volumi clonati, data Protection avanzata e altro ancora. 
---
= Scenari vari per la fatturazione Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comprendere la fatturazione Keystone per configurazioni specifiche nella versione 3 (v3) può aiutarti a ottimizzare l'utilizzo del servizio e a gestire i costi.  Le configurazioni includono volumi clonati, volumi temporanei, destinazioni SnapMirror , LUN e volumi di sistema/root.



== Fatturazione per volumi clonati

Se i volumi vengono clonati in ONTAP e utilizzati per il backup e il ripristino dei dati, è possibile continuare a utilizzare i cloni senza alcun pagamento aggiuntivo. Tuttavia, vengono addebitati i volumi clonati utilizzati per qualsiasi altro scopo dell'azienda per un periodo di tempo esteso.

Tenere presente quanto segue:

* I volumi clonati non possono essere caricati purché le loro dimensioni siano inferiori al 10% del volume principale (la capacità fisica utilizzata nel volume clone rispetto alla capacità fisica utilizzata nel volume principale).
* Non è previsto un periodo di grazia di 24 ore per i volumi clonati. Viene considerata solo la dimensione del clone.
* Una volta che il volume clone supera il 10% delle dimensioni fisiche dell'immagine principale, il clone viene fatturato come volume standard (capacità logica utilizzata).




== Fatturazione per volumi temporanei

Occasionalmente, i volumi temporanei (TMP) vengono creati da ONTAP durante lo spostamento dei volumi. Questi volumi temporanei sono di breve durata e il consumo su questi volumi non viene misurato per la fatturazione.



== Fatturazione per destinazioni SnapMirror

Il prezzo dei volumi di destinazione SnapMirror, sia per il disaster recovery che per la conservazione a lungo termine, si basa sul livello di servizio prestazionale assegnato alla destinazione. Non sono previsti costi aggiuntivi per la protezione dei dati.



== Fatturazione per LUN

Per le LUN, la fatturazione si basa sui livelli di servizio delle prestazioni del volume.



== Volumi di sistema e root

I volumi di sistema e root vengono monitorati come parte del monitoraggio generale del servizio Keystone, ma non vengono conteggiati o fatturati. Il consumo su questi volumi è esentato per la fatturazione.



== Fatturazione per destinazioni SnapMirror

I prezzi per il volume di destinazione SnapMirror sono regolati dalla policy di QoS adattiva per il livello di servizio assegnato all'origine. Tuttavia, se l'origine non dispone di una policy di QoS adattiva associata, la destinazione viene fatturata in base al livello di servizio più basso disponibile.



== Fatturazione per LUN

Per i LUN viene seguito lo stesso schema di fatturazione utilizzato per i volumi governati da policy di QoS adattive. Se nei LUN sono impostate policy di QoS adattive separate, allora:

* La dimensione del LUN viene conteggiata per il consumo in base al livello di servizio associato a tale LUN.
* L'eventuale spazio rimanente nel volume viene addebitato in base alla policy di QoS adattiva del livello di servizio impostato sul volume.




== Volumi di sistema e root

I volumi di sistema e root vengono monitorati come parte del monitoraggio generale del servizio Keystone, ma non vengono conteggiati o fatturati. Il consumo su questi volumi è esentato per la fatturazione.
