---
sidebar: sidebar 
permalink: concepts/misc-volume-billing-v2.html 
keywords: Billing and miscellaneous scenarios 
summary: Scopri la fatturazione di Keystone per configurazioni specifiche, tra cui volumi clonati, data Protection avanzata e altro ancora. 
---
= Scenari vari per la fatturazione Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comprendere la fatturazione Keystone per configurazioni specifiche nella versione 2 (v2) può aiutarti a ottimizzare l'utilizzo del servizio e a gestire i costi. Le configurazioni includono volumi clonati, protezione avanzata dei dati, volumi temporanei, policy QoS, destinazioni SnapMirror, LUN e volumi di sistema/root.



== Fatturazione per volumi clonati

Se i volumi vengono clonati in ONTAP e utilizzati per il backup e il ripristino dei dati, è possibile continuare a utilizzare i cloni senza alcun pagamento aggiuntivo. Tuttavia, vengono addebitati i volumi clonati utilizzati per qualsiasi altro scopo dell'azienda per un periodo di tempo esteso.

Tenere presente quanto segue:

* I volumi clonati non possono essere caricati purché le loro dimensioni siano inferiori al 10% del volume principale (la capacità fisica utilizzata nel volume clone rispetto alla capacità fisica utilizzata nel volume principale).
* Non è previsto un periodo di grazia di 24 ore per i volumi clonati. Viene considerata solo la dimensione del clone.
* Una volta che il volume clone supera il 10% delle dimensioni fisiche dell'immagine principale, il clone viene fatturato come volume standard (capacità logica utilizzata).




== Fatturazione per una protezione dei dati avanzata

La protezione dei dati avanzata sfrutta NetApp MetroCluster per eseguire il mirroring dei dati tra due cluster fisicamente separati. Per gli aggregati mirrorati di MetroCluster, i dati vengono scritti due volte, una volta su ciascun cluster. Il servizio Keystone addebita i costi di consumo su ciascun lato in modo indipendente, con la conseguenza di due record di consumo identici. I costi aggiuntivi vengono applicati a tutte le capacità dell'abbonamento, indipendentemente dal fatto che i dati siano all'origine o siano dati mirrorati o senza mirror.

Se si monitorano i cluster tramite Gestore di sistema di ONTAP (Gestore di sistema) o Active IQ Unified Manager (Gestore unificato), potrebbe verificarsi una discrepanza tra il consumo riportato su questi strumenti e Keystone. System Manager e Unified Manager non riportano i volumi sul cluster mirrorato (remoto) e, in questo modo, riporta la metà delle metriche di consumo riportate dal servizio Keystone.

.Esempio:
I siti A e B vengono configurati in una configurazione MetroCluster. Quando un utente crea un volume di 10 TB nel sito A, viene creato un volume identico di 10 TB nel sito B. Keystone identifica 10 TB di consumo in ogni sito, per un aumento totale di 20 TB. System Manager e Unified Manager segnalano un volume 10TB creato nel sito A, ma non un volume 10TB nel sito B.

Inoltre, tutti i volumi creati su un sistema Keystone con data Protection avanzata verranno conteggiati per il consumo di data Protection avanzata, indipendentemente dal fatto che tali volumi siano mirrorati o meno.



== Fatturazione per volumi temporanei

Occasionalmente, i volumi temporanei (TMP) vengono creati da ONTAP durante lo spostamento dei volumi. Questi volumi temporanei sono di breve durata e il consumo su questi volumi non viene misurato per la fatturazione.



== Policy di fatturazione e QoS adattivi

Keystone misura il consumo in base ai livelli di servizio. Ogni livello di servizio è associato a una specifica policy di qualità del servizio (QoS) adattativa. Durante l'implementazione, sarai informato dei dettagli di ogni policy di QoS adattiva per i servizi Keystone sottoscritti. Durante le operazioni di gestione dello storage, assicurati che i tuoi volumi abbiano assegnate le policy di QoS adattive appropriate in base ai livelli di servizio sottoscritti per evitare fatturazione imprevista. Per ulteriori informazioni sui criteri QoS adattativi in ONTAP, vedere link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garantire il throughput con la panoramica QoS"^].



== Fatturazione per destinazioni SnapMirror

I prezzi per il volume di destinazione SnapMirror sono regolati dalla policy di QoS adattiva per il livello di servizio assegnato all'origine. Tuttavia, se l'origine non dispone di una policy di QoS adattiva associata, la destinazione viene fatturata in base al livello di servizio più basso disponibile.



== Fatturazione per LUN

Per i LUN viene seguito lo stesso schema di fatturazione utilizzato per i volumi governati da policy di QoS adattive. Se nei LUN sono impostate policy di QoS adattive separate, allora:

* La dimensione del LUN viene conteggiata per il consumo in base al livello di servizio associato a tale LUN.
* L'eventuale spazio rimanente nel volume viene addebitato in base alla policy di QoS adattiva del livello di servizio impostato sul volume.




== Volumi di sistema e root

I volumi di sistema e root vengono monitorati come parte del monitoraggio generale del servizio Keystone, ma non vengono conteggiati o fatturati. Il consumo su questi volumi è esentato per la fatturazione.
