---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone offre un modello pay-as-you-grow per le tue esigenze di consumo flessibili e scalabili. 
---
= Scopri i prezzi Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il servizio di abbonamento NetApp Keystone STaaS con pagamento in base al consumo offre un consumo flessibile e scalabile con prezzi prevedibili e anticipati per le tue esigenze di storage.

Keystone ti offre i seguenti servizi di fatturazione:

* È possibile pagare in base alla capacità impegnata di IOPS e latenza per soddisfare diverse esigenze di carico di lavoro. I diversi livelli di servizio delle prestazioni (Extreme, Premium, Standard, Value, Object e Cloud Volumes ONTAP) consentono di gestire lo storage in base al livello di servizio delle prestazioni acquistato.
* Presenta una fatturazione prevedibile per la capacità impegnata e pay-per-use per l'utilizzo della capacità variabile (burst).
* Puoi scegliere un prezzo bundle per hardware, sistema operativo core e supporto per un prezzo CIB/dollari. Per ogni tipo di archiviazione, servizio di archiviazione unificato, a blocchi, ottimizzato, a oggetti o cloud, viene fornita un'unica fattura.
* È possibile selezionare una durata flessibile per i servizi e le opzioni di pagamento, ad esempio mensile, trimestrale, semestrale o annuale.


La fatturazione di Keystone si basa sulla capacità impegnata e sul consumo variabile di burst.

Per informazioni sulle diverse capacità supportate in Keystone, vedere link:../concepts/supported-storage-capacity.html["Capacità di storage supportate in Keystone"].

*Informazioni correlate*

* link:../concepts/committed-capacity-billing.html["Fatturazione basata sulla capacità impegnata"]
* link:../concepts/consumed-capacity-billing.html["Misurazione basata sulla capacità consumata"]
* link:../concepts/burst-consumption-billing.html["Fatturazione basata sul consumo burst"]
* link:../concepts/misc-volume-billing.html["Fatturazione basata su diversi tipi di volume"]
* link:../concepts/billing-schedules.html["Pianificazioni di fatturazione"]

