---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystone utilizza la QoS dello storage per garantire che le applicazioni ottengano performance coerenti e prevedibili. 
---
= Qualità del servizio di storage in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone utilizza la quality of service (QoS) dello storage per garantire che le applicazioni ottengano performance coerenti e prevedibili. Senza la qualità del servizio, alcuni workload, come quelli per il boot di sistemi multipli, potrebbero consumare la maggior parte delle risorse o tutte le risorse per un periodo di tempo e influire su altri workload.

Per informazioni su QoS, vedere https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garantire il throughput con la panoramica QoS"^].



== QoS adattiva

La QoS adattiva (AQoS) viene utilizzata dai servizi Keystone per mantenere dinamicamente il rapporto IOPS/TIB in base alle dimensioni del volume. Per informazioni sui criteri AQoS, vedere https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["Informazioni su QoS adattiva"^].

Keystone offre policy AQoS che è possibile configurare una volta che il cluster è in produzione. Assicurarsi che tutti i volumi siano associati alle policy AQoS corrette già create e disponibili nel sistema.

Un volume ONTAP non è conforme se non è stato applicato un criterio AQoS. Un volume senza policy QoS è l'ultimo dell'elenco di priorità per il sistema a fornire tutte le operazioni input-output disponibili. Tuttavia, se sono disponibili operazioni input-output, il volume potrebbe consumare tutti gli iOS disponibili.


NOTE: Se non sono state applicate policy AQoS ai volumi, tali volumi verranno misurati e addebitati al livello di servizio più elevato in base all'abbonamento. Ciò potrebbe causare cariche di burst non intense.



== Impostazioni QoS adattive

Le impostazioni di QoS adattivo (AQoS) variano in base ai livelli di servizio.

|===


| *Nome policy* | *Estrema* | *Premium* | *Prestazioni* | *Standard* | *Valore* 


| *IOPS previsti* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Allocazione IOPS prevista* 5+| Spazio allocato 


| *IOPS di picco* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Allocazione IOPS massima* 5+| Spazio utilizzato 


| *Dimensione blocco* 5+| 32.000 
|===


== Configurazione del gruppo di criteri QoS adattivi

È possibile configurare policy QoS adattive (AQoS) per scalare automaticamente un limite di throughput o un volume in base alle dimensioni. Non tutti i livelli di servizio di Keystone sono allineati con le policy QoS predefinite di ONTAP. È possibile creare policy QoS personalizzate per tali criteri. Per la configurazione di un criterio, tenere presente quanto segue:

* *Policy group name*: Il nome del gruppo di criteri AQoS. Ad esempio, `Keystone_extreme`.
* *VServer*: Il nome del VServer o della VM di storage (macchina virtuale di storage).
* *IOPS previsti*: Il numero minimo di IOPS, per TIB allocati per volume, che il sistema tenta di fornire quando è disponibile un numero sufficiente di IOPS di sistema.
* *Peak IOPS*: Il numero massimo di IOPS, per TIB utilizzato per volume, che il sistema consente al volume di raggiungere prima di ridurre gli IOPS attraverso l'iniezione di latenza.
* *Allocazione IOPS prevista*: Questo parametro controlla se gli IOPS previsti disponibili per il volume si basano sulle dimensioni allocate o utilizzate del volume. In Keystone, questo si basa sullo spazio allocato.
* *Peak IOPS allocation* (allocazione IOPS picco): Questo parametro controlla se gli IOPS di picco disponibili per il volume si basano sulle dimensioni allocate o utilizzate del volume. In Keystone, questo si basa sullo spazio utilizzato.
* *IOPS minimi assoluti*: Il numero più basso di IOPS previsti che verranno applicati a un volume se le dimensioni del volume sono molto piccole e altrimenti risulterebbero in un numero inaccettabile di IOPS. Questo valore predefinito è 1,000 per `Extreme`, 500 per `Premium`e 250 per `Performance`e 75 per `Standard` e. `Value` livelli di servizio.
+

NOTE: Non si tratta di densità IOPS (ad esempio, 75 IOPS/TIB), ma di un numero minimo assoluto di IOPS.



Per informazioni sulla densità io, vedere link:../concepts/metrics.html["Metriche e definizioni utilizzate nei servizi Keystone"]. Per ulteriori informazioni sui gruppi di criteri AQoS, vedere https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["Utilizzare gruppi di policy QoS adattivi"^].



== Impostazioni delle policy QoS adattive

Le impostazioni delle policy di QoS adattive (AQoS) per ciascun livello di servizio sono descritte nelle sezioni seguenti. Le dimensioni minime e massime del volume per ciascun livello di servizio qui fornito consentono di ottenere valori ottimali di IOPS e latenza per un volume. La creazione di un numero eccessivo di volumi al di fuori di queste linee guida potrebbe avere un impatto negativo sulle performance di tali volumi.



=== Impostazioni per il livello di servizio estremo

Impostazioni e comandi per il livello di servizio estremo:

* Esempio di comando:


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* Dimensioni minime del volume: 100 GiB, 0,1 TiB
* Dimensione massima del volume: 10 TiB




=== Impostazioni per il livello di servizio Premium

Impostazioni e comandi per il livello di servizio Premium:

* Esempio di comando:


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* Dimensioni minime del volume: 500 GiB, 0,5 TiB
* Dimensione massima del volume: 50 TiB




=== Impostazioni per il livello di servizio Performance

Impostazioni e comandi per il livello di servizio Performance:

* Esempio di comando:


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* Dimensioni minime del volume: 500 GiB, 0,5 TiB
* Dimensione massima del volume: 80 TiB




=== Impostazioni per il livello di servizio Standard

Impostazioni e comandi per il livello di servizio Standard:

* Esempio di comando:


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Dimensione minima del volume: 1 TiB
* Dimensione massima del volume: 100 TiB




=== Impostazioni per il livello di servizio Value

Impostazioni e comandi per il livello di servizio Value:

* Esempio di comando:


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Dimensione minima del volume: 1 TiB
* Dimensione massima del volume: 100 TiB




== Calcolo della dimensione del blocco

Prendere nota di questi punti prima di calcolare la dimensione del blocco utilizzando le seguenti impostazioni:

* IOPS/TIB = Mbps/TIB diviso per (dimensione blocco * 1024)
* La dimensione del blocco è in KB/io
* TIB = 1024 GiB; GiB = 1024 MIB; MiB = 1024 KiB; KiB = 1024 byte; come da base 2
* TB = 1000 GB; GB = 1000 MB; MB = 1000 KB; KB = 1000 byte; secondo la base 10


.Calcolo delle dimensioni dei blocchi di esempio
Ad esempio, per calcolare il throughput per un livello di servizio `Extreme` livello di servizio:

* IOPS massimo: 12,288
* Dimensione del blocco per i/o: 32 KB
* Throughput massimo = (12288 * 32 * 1024) / (1024*1024) = 384 MBps/TIB


Se un volume contiene 700GiB di dati logici utilizzati, il throughput disponibile sarà:

`Maximum throughput = 384 * 0.7 = 268.8MBps`
