---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS per la versione 3 offre capacità di archiviazione a livelli di servizio predefiniti. Ogni volume gestito da Keystone è associato a un livello di servizio. 
---
= Livelli di servizio prestazionali a Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS per la versione 3 (v3) offre capacità di archiviazione dati a livelli di servizio prestazionali predefiniti. A ciascun volume gestito dai servizi Keystone è associato un livello di servizio prestazionale.

Un abbonamento può prevedere più piani tariffari, ognuno dei quali corrisponde a un livello di servizio di performance. Ogni piano tariffario prevede una capacità impegnata per livello di servizio di performance.

Un livello di servizio prestazionale può avere più istanze, ciascuna delle quali rappresenta un array di storage separato assegnato a tale livello di servizio prestazionale nell'ambiente del cliente. Ogni livello di servizio prestazionale è definito da operazioni di input/output al secondo (IOPS), throughput (GBps) e latenza (ms), con queste metriche misurate e applicate per ogni istanza del livello di servizio prestazionale.

È possibile selezionare i livelli di servizio prestazionali in base al proprio ambiente di storage e alle esigenze di storage e consumo. I livelli di servizio prestazionali di base sono disponibili per impostazione predefinita. Sono inoltre disponibili livelli di servizio prestazionali specifici, se si sono optati per servizi aggiuntivi. Ad esempio, per il servizio aggiuntivo di protezione avanzata dei dati, al proprio abbonamento viene assegnato il livello di servizio prestazionale _Advanced Data-Protect_.


TIP: È disponibile una descrizione dettagliata del servizio per i livelli di servizio delle prestazioni NetApp Keystone STaaS  https://www.netapp.com/services/keystone/terms-and-conditions/["qui"^] .

I livelli di servizio delle prestazioni di base per i tipi di storage supportati, ovvero servizi unificati, ottimizzati per blocchi, oggetti e cloud, sono descritti nelle sezioni seguenti:



== Livelli di servizio prestazionali per l'archiviazione unificata

*Protocolli supportati*: FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3

|===


| *Livello di servizio delle prestazioni* (tutte le specifiche per istanza di livello di servizio delle prestazioni) | *Estrema* | *Premium* | *Standard* | *Valore* 


| *Tipi di workload di esempio* | AI/ML, HPC, database InMem | Analisi, EDA, OLTP | OLAP, IoT, Contenitori | Backup, Archivio 


| *IOPS massimi*^1^ | 1M | 550 mila | 500 mila | NA 


| *Massimo GBps* | 40 | 20 | 20 | NA 


| *Target 90^th^ latenza percentile* | <=1 ms | <=1 ms | <=4 ms | >4 ms 


| *Capacità minima impegnata* | 50 TIB | 50 TIB | 100 TIB | 100 TIB 


| *Aumento incrementale della capacità impegnata* 4+| 25TiB 


| *Tipo di capacità impegnata e misurata* 4+| Logico o fisico 
|===


== Livelli di servizio prestazionali per l'archiviazione ottimizzata a blocchi

*Protocolli supportati*: NVMe/TCP, NVMe/FC, FC, iSCSI

|===


| *Livello di servizio delle prestazioni* (tutte le specifiche per istanza di livello di servizio delle prestazioni) | *Estrema* | *Premium* 


| *Tipi di workload di esempio* 2+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *IOPS massimi*^1^ | 850 mila | 450 mila 


| *Massimo GBps* | 65 | 25 


| *Target 90^th^ latenza percentile* | <=1 ms | <=1 ms 


| *Capacità minima impegnata* | 50 TIB | 50 TIB 


| *Aumento incrementale della capacità impegnata* 2+| 25TiB 


| *Tipo di capacità impegnata e misurata* 2+| Logico o fisico 
|===

NOTE: ^1^Obiettivi reciprocamente esclusivi. Le prestazioni effettive possono variare in base a vari fattori, tra cui la versione del sistema operativo, l'hardware, il tipo di carico di lavoro e il numero di operazioni simultanee.



=== Ulteriori informazioni sui livelli di servizio delle prestazioni per l'archiviazione unificata e ottimizzata a blocchi

Le metriche del livello di servizio delle prestazioni di base dipendono dalle seguenti condizioni:

* I livelli di servizio delle prestazioni supportano ONTAP 9.8 e versioni successive.
* Per un'archiviazione unificata,
+
** *IOPS*: Per ONTAP 9.16.1 con NFS, ogni istanza del livello di prestazioni supporta l'accesso casuale con un rapporto di lettura del 70% e di scrittura del 30%, una dimensione del blocco di 8 KB e una latenza di 1 ms (4 ms per Standard).
** *Capacità*: per ONTAP 9.16.1 con NFS, ogni istanza del livello di prestazioni supporta l'accesso sequenziale con lettura al 100% e una dimensione del blocco di 32 KB.


* Per l'archiviazione ottimizzata a blocchi,
+
** *IOPS*: Per ONTAP 9.16.1 con FCP, ogni istanza del livello di prestazioni supporta l'accesso casuale con un rapporto di lettura del 70% e di scrittura del 30%, una dimensione del blocco di 8 KB e una latenza di 1 ms.
** *Rendimento*: per ONTAP 9.16.1 con FCP, ogni istanza del livello di prestazioni supporta l'accesso sequenziale con lettura al 100% e una dimensione del blocco di 64 KB.


* La latenza non include quanto segue:
+
** latenza dell'applicazione o dell'host
** latenza di rete del cliente da o verso le porte del controller
** Overhead associati al trasferimento dei dati nell'archivio di oggetti in caso di FabricPool


* I valori di latenza non sono applicabili alle operazioni di scrittura MetroCluster. Queste operazioni di scrittura dipendono dalla distanza dei sistemi remoti.
* _Gli IOPS previsti_ sono destinati a FabricPool solo se la policy di tiering è impostata su "nessuno" e non ci sono blocchi nel cloud. _Gli IOPS previsti_ sono destinati a volumi che non sono in una relazione sincrona di SnapMirror.




== Livelli di servizio prestazionali per l'archiviazione di oggetti

*Protocollo supportato*: S3

|===


| *Livello di servizio prestazionale* | *Standard* | *Valore* 


| *Capacità minima impegnata per ordine* | 200 TIB | 500 TIB 


| *Aumento incrementale della capacità impegnata* | 25 TIB | 100 TIB 


| *Tipo di capacità impegnata e misurata* 2+| Fisico 
|===


== Cloud storage

*Protocolli supportati*: NFS, CIFS, iSCSI e S3 (solo AWS e Azure)

|===


| *Livello di servizio prestazionale* | Cloud Volumes ONTAP 


| *Capacità minima impegnata per ordine* | 4 TIB 


| *Aumento incrementale della capacità impegnata* | 1 TIB 


| *Tipo di capacità impegnata e misurata* | Logico 
|===
[NOTE]
====
* I servizi nativi del cloud, come il calcolo, lo storage, il networking, sono fatturati dai cloud provider.
* Questi servizi dipendono dalle caratteristiche di cloud storage e calcolo.


====
*Informazioni correlate*

* link:../concepts/supported-storage-capacity.html["Capacità di storage supportate"]
* link:..//concepts/metrics.html["Metriche e definizioni utilizzate nei servizi Keystone"]
* link:../concepts/pricing.html["Prezzo Keystone"]

