---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: Utilizza il NetApp Support Site per creare una richiesta di supporto o trovare le informazioni di contatto per i tuoi abbonamenti Keystone. 
---
= Ottieni aiuto con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp fornisce ai clienti Keystone servizi operativi. I clienti ricevono un Keystone Success Manager (KSM) dedicato, opzioni di contatto diretto con il supporto e monitoraggio proattivo tramite la soluzione ITOM.



== NetApp supporto tecnico

NetApp fornisce servizi operativi da remoto ai clienti Keystone. Questi servizi comprendono una vasta gamma di attività di gestione dello storage, tra cui la gestione degli asset e della configurazione, la gestione della capacità e delle prestazioni, la gestione delle modifiche, la gestione degli eventi e degli incidenti, l'evasione delle richieste di servizio e la reportistica.

.Keystone Success Manager
Il tuo KSM collabora a stretto contatto con te sui tuoi servizi Keystone e fornisce report di fatturazione e operativi settimanali o mensili. Le responsabilità specifiche sono definite nel tuo accordo NetApp Keystone.



== Contatta il supporto

Se riscontri un problema con il tuo abbonamento Keystone, accedi al link:https://support.netapp.com["Sito di supporto NetApp"^] utilizzando le tue credenziali NSS per creare una richiesta di supporto tecnico.

Se non si dispone di un login NSS, link:https://mysupport.netapp.com/site/user/registration["registra il tuo account"^] utilizzare il numero di serie (SN) di uno dei nodi del proprio abbonamento.

Per istruzioni dettagliate con schermate illustrative, vedere link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["Come aprire un caso di supporto tecnico"^].

Se preferisci parlare direttamente con un rappresentante del supporto tecnico, chiama uno dei seguenti numeri:

* Stati Uniti / Canada: 888 463 8277
* Europa: 00 800 44 638277
* India: 000 800 100 8948
* Altri dati globali: link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== Monitoraggio del supporto

NetApp utilizza la soluzione di monitoraggio ITOM per monitorare in modo proattivo lo stato di salute dei tuoi prodotti e dei servizi in abbonamento e connettersi all'ambiente NetApp Keystone per la risoluzione dei problemi.



== Risorse aggiuntive

Per ulteriori informazioni sui servizi Keystone, consulta:

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["Documentazione del prodotto NetApp"^]


*Informazioni correlate*

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["Come identificare il numero di serie della piattaforma ONTAP"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["Quale numero di serie utilizzare quando si crea un caso di supporto tecnico StorageGRID"^]

