---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: I servizi Keystone STaaS supportano ONTAP e StorageGRID. 
---
= Storage supportato in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il servizio Keystone STaaS supporta l'archiviazione unificata, ottimizzata per blocchi e di oggetti di NetApp e Cloud Volumes ONTAP.

Le opzioni di archiviazione supportate sono:

* *Archiviazione unificata*: include archiviazione di file, blocchi e oggetti S3, disponibile sui sistemi NetApp ONTAP AFF e FAS.
* *Archiviazione ottimizzata a blocchi*: include l'archiviazione a blocchi disponibile sui sistemi NetApp ONTAP ASA .
* *Archiviazione oggetti*: include l'archiviazione oggetti disponibile sui sistemi NetApp StorageGRID.


Keystone STaaS offre servizi standard e opzionali per il tuo storage.

*Servizi standard Keystone STaaS*: I servizi standard sono inclusi nell'abbonamento base e non vengono addebitati separatamente.

*Servizi aggiuntivi Keystone STaaS*: Servizi opzionali a pagamento che offrono utility e vantaggi aggiuntivi rispetto ai servizi di abbonamento standard Keystone STaaS.

I servizi Keystone STaaS possono essere utilizzati contemporaneamente. Ad esempio, un abbonamento all'archiviazione cloud può avere la stessa durata degli abbonamenti all'archiviazione unificata, ottimizzata a blocchi e a oggetti. Un servizio cloud può essere incluso in qualsiasi momento durante il periodo di validità di un abbonamento allo storage esistente. Tuttavia, se non si prevede di rinnovare un abbonamento esistente all'archiviazione unificata, ottimizzata a blocchi o a oggetti, non è possibile aggiungere un abbonamento all'archiviazione cloud durante gli ultimi 90 giorni dell'abbonamento.



== Servizi per l'archiviazione unificata, ottimizzata a blocchi e a oggetti

I servizi Keystone STaaS per l'archiviazione unificata, ottimizzata a blocchi e a oggetti supportano più funzionalità e protocolli e sono descritti nella tabella seguente:

|===
| Storage | Piattaforma | Protocolli | Funzionalità supportate 


 a| 
Storage unificato
 a| 
ONTAP
 a| 
NFS e CIFS
 a| 
Supporta tutte le funzionalità di ONTAP One



 a| 
Archiviazione ottimizzata a blocchi
 a| 
ONTAP
 a| 
FC e iSCSI
 a| 
Supporta tutte le funzionalità di ONTAP One



 a| 
Storage a oggetti
 a| 
StorageGRID
 a| 
S3
 a| 
Supporta tutte le funzionalità di ONTAP One

|===
Per saperne di più su ONTAP One, fare riferimento a link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Panoramica delle licenze ONTAP"^] E link:https://www.netapp.com/blog/ontap-one/["ONTAP One: tutta la potenza di ONTAP, ora tutto in uno"^] .



== Servizi per il cloud storage

Keystone STaaS offre servizi di cloud storage. Keystone STaaS supporta le funzionalità di gestione dei dati Cloud Volumes ONTAP su Amazon Web Services (AWS), Microsoft Azure e piattaforma cloud Google.


NOTE: I servizi di calcolo, storage e rete basati su hyperscalar richiesti da Cloud Volumes ONTAP non sono forniti da NetApp come parte degli abbonamenti STaaS Keystone; questi abbonamenti devono essere acquistati direttamente dai provider di servizi cloud hyperscalar.
