---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Scopri i tipi di capacità di archiviazione supportati dal servizio NetApp Keystone STaaS per la versione 3. 
---
= Capacità di storage supportate in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il servizio NetApp Keystone STaaS supporta diversi tipi di capacità di archiviazione. La comprensione di questi diversi termini di capacità può essere utile durante l'utilizzo Keystone.



== Capacità logica

Si tratta della quantità di capacità di archiviazione richiesta per archiviare i dati utente prima che vengano applicate le efficienze dei dati fornite dall'array di archiviazione.



== Capacità impegnata

La capacità logica minima fatturata ogni mese durante l'abbonamento:

* La capacità è impegnata per ogni livello di servizio prestazionale.
* Durante il periodo di validità del contratto è possibile aggiungere capacità impegnata e livelli di servizio aggiuntivi.




=== Modifiche alla capacità impegnata

Durante il periodo di validità di un abbonamento, è possibile modificare le capacità assegnate. Tuttavia, esistono alcune condizioni preliminari:

* La capacità impegnata può essere ridotta in base a determinate condizioni. Per ulteriori informazioni, vedere link:../concepts/capacity-requirements.html["Riduzione della capacità"].
* La capacità impegnata non può essere aumentata di 90 giorni prima della scadenza dell'abbonamento, a meno che l'abbonamento non venga rinnovato per un ulteriore periodo di 12 mesi.
* Puoi richiedere modifiche alla capacità impegnata tramite la Console o dal tuo Keystone Success Manager (KSM). Per informazioni sulla richiesta di modifiche, vederelink:../concepts/gssc.html["Supporto NetApp Keystone"] .




== Capacità consumata

La capacità consumata si riferisce alla capacità (in TIB dello storage) attualmente consumata nel servizio. Viene calcolato in modo diverso in base al tipo di archiviazione:

* *Archiviazione unificata o ottimizzata per blocchi*: la capacità consumata viene calcolata in base al tipo di capacità (logica o fisica) selezionata durante il processo di ordinazione.  Il calcolo viene eseguito per istanza del livello di servizio delle prestazioni.
+
.. *Capacità logica*: È la somma di:
+
*** Capacità logica misurata, prima dell'efficienza dei dati dell'array di archiviazione, per archiviare tutte le istanze e i tipi di dati dei clienti, come copie, copie speculari, versioni e cloni.
*** Capacità fisica utilizzata per archiviare metadati e dati differenziali di snapshot e determinati cloni.
*** Qualsiasi capacità fisica di grandi dimensioni.


.. *Capacità fisica*: È la somma di:
+
*** Capacità fisica misurata, dopo l'efficienza dei dati dell'array di archiviazione, per archiviare tutte le istanze e i tipi di dati dei clienti, come copie, copie speculari, versioni, cloni.
*** Capacità fisica utilizzata per archiviare metadati e dati differenziali degli snapshot.
*** Qualsiasi capacità fisica di grandi dimensioni.




* *Archiviazione di oggetti*: la capacità consumata viene calcolata come la quantità di capacità fisica misurata utilizzata per archiviare tutte le istanze e i tipi di dati dei clienti su tutti i nodi. Questo calcolo si basa sulle policy di gestione del ciclo di vita delle informazioni (ILM) configurate.
* *Cloud Volumes ONTAP*: la capacità consumata viene calcolata come la quantità di capacità fornita e misurata di tutti i volumi Cloud Volumes ONTAP.




== Capacità di burst

Il servizio NetApp Keystone STaaS consente di utilizzare capacità aggiuntiva oltre a quella impegnata per un livello di servizio di performance. Questo è definito utilizzo di capacità burst.

Prendere nota di questi punti:

* La capacità burst è concordata nell'accordo Keystone. Di solito è impostato fino al 20% in più rispetto alla capacità impegnata, per istanza del livello di servizio delle prestazioni, con opzioni aggiuntive disponibili per selezionare limiti di capacità burst del 40% o del 60% della capacità impegnata.
* Il consumo di capacità burst viene fatturato alla stessa tariffa della capacità impegnata corrispondente al livello di servizio prestazionale selezionato.
* I servizi Keystone STaaS prevedono un periodo di deroga di 60 giorni a partire dalla data di inizio.




== Capacità fatturata

Bolletta mensile = (capacità impegnata [TIB] * tasso impegnato [ USD/TIB]) + (capacità burst media giornaliera [TIB] * tasso burst [ USD/TIB]). La fattura mensile contiene un costo minimo in base alla capacità impegnata.

La fattura mensile varia oltre la tariffa minima in base al consumo medio giornaliero di capacità burst.
