---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: I servizi Keystone STaaS supportano ONTAP e StorageGRID. 
---
= Storage supportato in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS supporta storage unificato, ottimizzato per blocchi, AFX e storage a oggetti sulle piattaforme NetApp, nonché Cloud Volumes ONTAP. Ogni tipo di storage è definito come tipo di storage dati (DST) ed è disponibile con i servizi standard inclusi nell'abbonamento base, insieme a servizi aggiuntivi opzionali.



== Keystone STaaS servizi standard e aggiuntivi

Keystone STaaS offre servizi standard e opzionali per il tuo storage.

*Servizi standard Keystone STaaS*: I servizi standard sono inclusi nell'abbonamento base e non vengono addebitati separatamente.

*Servizi aggiuntivi Keystone STaaS*: Servizi opzionali a pagamento che offrono utility e vantaggi aggiuntivi rispetto ai servizi di abbonamento standard Keystone STaaS.

È possibile abbonarsi contemporaneamente a più servizi Keystone STaaS. Quando si aggiungono servizi cloud a un abbonamento, questi condividono la stessa durata delle soluzioni unificate, ottimizzate per i blocchi e/o dello storage a oggetti. Un servizio cloud può essere aggiunto in qualsiasi momento durante la validità di un abbonamento storage attivo. Tuttavia, se non si prevede di rinnovare un abbonamento esistente per lo storage unificato, ottimizzato a blocchi o a oggetti, non è possibile aggiungere un servizio cloud negli ultimi 90 giorni di validità di tale abbonamento.


NOTE: L'abbonamento AFX è autonomo e non può essere combinato con unified, block-optimized o storage a oggetti nello stesso abbonamento. Se hai bisogno di AFX insieme ad altri tipi di storage, devi sottoscriverli come abbonamenti separati.



== Tipi di archiviazione dati supportati

I servizi Keystone STaaS per lo storage unificato, ottimizzato a blocchi, a oggetti e AFX supportano molteplici funzionalità e protocolli, descritti nella tabella seguente:

|===
| Tipo di archiviazione dati | Descrizione | Piattaforma | Protocolli | Funzionalità supportate 


 a| 
Unificato
 a| 
Include storage file, a blocchi e S3 a oggetti
 a| 
ONTAP sui sistemi AFF e FAS
 a| 
FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3
 a| 
Supporta tutte le funzionalità di ONTAP One



 a| 
Ottimizzato a blocchi
 a| 
Include storage a blocchi
 a| 
NVMe/TCP, NVMe/FC, FC, iSCSI
 a| 
FC e iSCSI
 a| 
Supporta tutte le funzionalità di ONTAP One for SAN



 a| 
AFX
 a| 
Include storage file e storage a oggetti su una piattaforma di storage disaggregata
 a| 
ONTAP sui sistemi AFX
 a| 
NFSv3, NFSv4/RDMA, pNFS, SMB, S3
 a| 
Supporta tutte le funzionalità di ONTAP One



 a| 
Oggetto
 a| 
Include storage a oggetti
 a| 
StorageGRID
 a| 
S3
 a| 
Supporta tutte le funzionalità di StorageGRID

|===
Per saperne di più su ONTAP One, fare riferimento a link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Panoramica delle licenze ONTAP"^] E link:https://www.netapp.com/blog/ontap-one/["ONTAP One: tutta la potenza di ONTAP, ora tutto in uno"^] .



== Servizi per il cloud storage

Keystone STaaS offre servizi di cloud storage. Keystone STaaS supporta le funzionalità di gestione dei dati Cloud Volumes ONTAP su Amazon Web Services (AWS), Microsoft Azure e piattaforma cloud Google.


NOTE: I servizi di calcolo, storage e rete basati su hyperscaler richiesti da Cloud Volumes ONTAP non sono forniti da NetApp come parte degli abbonamenti Keystone STaaS; questi abbonamenti devono essere acquistati direttamente dai fornitori di servizi cloud hyperscaler.
