---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Scopri i tipi di capacità dello storage supportati dal servizio STaaS NetApp Keystone. 
---
= Capacità di storage supportate in Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il servizio NetApp Keystone STaaS supporta diversi tipi di capacità dello storage. Comprendere questi termini diversi di capacità può aiutarti durante l'utilizzo di Keystone.



== Capacità logica

Si tratta dei dati inseriti nell'infrastruttura Keystone da un cliente. Tutte le capacità Keystone si riferiscono a una capacità logica. Ad esempio, se un file 1 TIB viene memorizzato nell'infrastruttura Keystone, è necessario acquistare un minimo di 1 TIB di capacità.



== Capacità impegnata

La capacità logica minima fatturata ogni mese durante l'abbonamento:

* La capacità viene impegnata in base a ciascun livello di servizio.
* È possibile aggiungere capacità impegnata e livelli di servizio aggiuntivi durante il periodo di validità.




=== Modifiche alla capacità impegnata

Durante il periodo di validità di un abbonamento, è possibile modificare le capacità assegnate. Tuttavia, esistono alcune condizioni preliminari:

* La capacità impegnata può essere ridotta in base a determinate condizioni. Per ulteriori informazioni, vedere link:../concepts/capacity-requirements.html["Riduzione della capacità"].
* La capacità impegnata non può essere aumentata di 90 giorni prima della scadenza dell'abbonamento, a meno che l'abbonamento non venga rinnovato per un ulteriore periodo di 12 mesi.
* È possibile richiedere modifiche alla capacità impegnata tramite l'interfaccia BlueXP o Keystone Success Manager (KSM). Per informazioni sulla richiesta di modifiche, vedere link:../concepts/gssc.html["NetApp Global Services Support Center"].




== Capacità consumata

La capacità consumata si riferisce alla capacità (in TIB dello storage) attualmente consumata nel servizio. Il servizio Keystone considera la somma delle dimensioni logiche utilizzate (non la capacità fisica utilizzata) di tutti i volumi su un determinato livello di servizio per calcolare la capacità consumata per quel livello di servizio.



== Capacità di burst

Il servizio Keystone consente di utilizzare capacità aggiuntiva oltre alla capacità impegnata per un livello di servizio. Questo è l'utilizzo della capacità burst. Prendere nota di questi punti:

* La capacità burst è concordata nell'accordo Keystone. In genere, viene impostato fino al 20% al di sopra della capacità impegnata e viene addebitato allo stesso tasso della capacità impegnata.
* La capacità di burst può essere consumata su base elastica e viene addebitata quotidianamente in base alla media consumata.




== Capacità fatturata

Bolletta mensile = (capacità impegnata [TIB] * tasso impegnato [ USD/TIB]) + (capacità burst media giornaliera [TIB] * tasso burst [ USD/TIB]). La fattura mensile contiene un costo minimo in base alla capacità impegnata.

La fattura mensile varia oltre la tariffa minima in base al consumo medio giornaliero di capacità burst.
