---
sidebar: sidebar 
permalink: concepts/usps.html 
keywords: netapp, keystone, US citizen support, USPS, Keystone Success Manager, USPS support 
summary: Il supporto protetto degli Stati Uniti è un servizio add-on che offre la fornitura e il supporto dei servizi Keystone in corso da parte dei cittadini degli Stati Uniti in territorio statunitense. 
---
= Ulteriori informazioni su USPS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
USPS (United States Protected Support) è un'offerta aggiuntiva per gli abbonamenti NetApp Keystone. Ti dà diritto a ricevere la consegna e il supporto dei servizi Keystone in corso dai cittadini degli Stati Uniti in territorio statunitense.

Leggi le seguenti sezioni per capire quali elementi degli abbonamenti sono vincolati da questo servizio add-on e sono forniti in base ai termini del contratto NetApp Keystone.Footnote:disclaimer 1[i servizi e le offerte qui descritti sono soggetti, limitati e regolati da un contratto Keystone pienamente eseguito.]



== Monitoraggio USPS NetApp

Il team di supporto NetApp USPS Keystone monitora la salute dei tuoi prodotti e dei servizi sottoscritti, fornisce supporto remoto e collabora con il tuo Keystone Success Manager. Tutto il personale che monitora i prodotti associati ai relativi ordini di abbonamento Keystone è U. S cittadini che operano sul suolo degli Stati Uniti.



== Keystone Success Manager

Il Keystone Success Manager (KSM) è un Cittadino che opera negli Stati Uniti suolo. Le loro responsabilità sono specificate nel Contratto NetApp Keystone.



== Attività di implementazione

Se disponibili, le attività di installazione e implementazione in sede e in remoto sono condotte da U.S. Cittadini negli Stati Uniti suolo. Nota a piè di pagina:esclusione di responsabilità[la disponibilità del personale appropriato per le attività in loco dipende dall'ubicazione geografica in cui vengono distribuiti i sistemi Keystone.]



== Supporto

Se disponibili, le attività di risoluzione dei problemi e supporto in loco necessarie sono condotte da U.S. Cittadini negli Stati Uniti suolo. nota a piè di pagina:disclaimer[]
