---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: 'Installare il software Keystone Collector dall"archivio del software YUM.' 
---
= Installare Keystone Collector su sistemi Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si può installare il software Keystone Collector su un server Linux usando un RPM o un pacchetto Debian. Seguire la procedura di installazione a seconda della distribuzione Linux in uso.

[role="tabbed-block"]
====
.Utilizzo di RPM
--
. SSH al server di Keystone Collector e passare a. `root` privilegio.
. Importa la firma pubblica Keystone :
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. Verificare che sia stato importato il certificato pubblico corretto controllando l'impronta digitale per Keystone Billing Platform nel database RPM:
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` L'impronta digitale corretta si presenta così:
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. Scarica il `keystonerepo.rpm` file:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. Verificare l'autenticità del file:
`rpm --checksig -v keystonerepo.rpm` La firma di un file autentico si presenta così:
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. Installare il file repository del software YUM:
`# yum install keystonerepo.rpm`
. Una volta installato Keystone repo, installare il pacchetto keystone-collector tramite YUM Package Manager:
+
`# yum install keystone-collector`

+
Per Red Hat Enterprise Linux 9, eseguire il seguente comando per installare il pacchetto keystone-collector: 
`# yum install keystone-collector-rhel9`



--
.Uso di Debian
--
. SSH al server Keystone Collector e privilegi più elevati `root`.
`sudo su`
. Scaricare il `keystone-sw-repo.deb` file:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Installare il file repository del software Keystone:
`# dpkg -i keystone-sw-repo.deb`
. Aggiornare l'elenco dei pacchetti:
`# apt-get update`
. Una volta installato Keystone repo, installare il pacchetto keystone-collector:
`# apt-get install keystone-collector`


--
====

NOTE: Una volta completata l'installazione, è possibile utilizzare l'utility Keystone Collector Management Terminal User Interface (TUI) per eseguire le attività di configurazione e monitoraggio. Per selezionare le opzioni e spostarsi all'interno dell'interfaccia telefonica utente, è possibile utilizzare diversi comandi della tastiera, ad esempio i tasti Invio e freccia. Vedere link:../installation/configuration.html["Configurare Keystone Collector"] e. link:../installation/monitor-health.html["Monitorare lo stato del sistema"] per informazioni.
