---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Problemi risolti nelle diverse release di Keystone STaaS 
---
= Problemi risolti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I problemi riscontrati nelle precedenti release dei servizi NetApp Keystone STaaS sono stati risolti nelle release successive. Queste sono le correzioni.

[cols="3*"]
|===
| Descrizione del problema | Dopo la correzione | Fissato in rilascio 


 a| 
Testo della descrizione comando non corretto per l'icona dell'indice *sequenza corrente* nella scheda *tendenza capacità*.
 a| 
Visualizza il testo della descrizione comandi corretto "_la quantità di capacità burst attualmente consumata. Nota: Si tratta del periodo di fatturazione corrente, non dell'intervallo di date selezionato._"
 a| 
28 marzo 2024



 a| 
Le informazioni sui volumi non conformi di AQoS e sui partner MetroCluster non sono disponibili per gli abbonamenti AutoSupport se i dati Keystone non sono presenti per 24 ore.
 a| 
Corretto
 a| 
28 marzo 2024



 a| 
Discrepanza occasionale nel numero di volumi non conformi AQoS elencati nelle schede *Volume Summary* e *Volume Details* se vi sono due livelli di servizio assegnati a un volume che soddisfa la conformità AQoS per un solo livello di servizio.
 a| 
Corretto
 a| 
28 marzo 2024



 a| 
Non sono disponibili informazioni nella scheda *risorse* per gli abbonamenti AutoSupport.
 a| 
Corretto
 a| 
14 marzo 2024



 a| 
Se MetroCluster e FabricPool sono stati abilitati in un ambiente in cui i piani di tasso per il tiering e lo storage a oggetti erano applicabili, i livelli di servizio potrebbero essere derivati in modo errato per i volumi mirror (sia i volumi costituenti che i volumi FabricPool).
 a| 
Ai volumi mirror vengono applicati livelli di servizio corretti.
 a| 
29 febbraio 2024



 a| 
Per alcune sottoscrizioni con un unico livello di servizio o piano tariffario, la colonna di conformità AQoS non era presente nell'output CSV dei report della scheda *volumi*.
 a| 
La colonna conformità è visibile nei report.
 a| 
29 febbraio 2024



 a| 
In alcuni ambienti MetroCluster, sono state rilevate anomalie occasionali nei diagrammi della densità degli IOPS nella scheda *Performance*. Ciò si è verificato a causa di una mappatura imprecisa dei volumi ai livelli di servizio.
 a| 
I grafici sono visualizzati correttamente.
 a| 
29 febbraio 2024



 a| 
L'indicatore di utilizzo per una registrazione del consumo di burst era visualizzato in ambra.
 a| 
L'indicatore viene visualizzato in rosso.
 a| 
13 dicembre 2023



 a| 
L'intervallo di date e i dati nelle schede Trend capacità, utilizzo corrente e prestazioni non sono stati convertiti in fuso orario UTC.
 a| 
L'intervallo di date per la query e i dati in tutte le schede viene visualizzato in ora UTC (fuso orario del server). Il fuso orario UTC viene inoltre visualizzato in corrispondenza di ciascun campo della data nelle schede.
 a| 
13 dicembre 2023



 a| 
Si è verificata una mancata corrispondenza tra la data di inizio e la data di fine tra le schede e i report CSV scaricati.
 a| 
Fisso.
 a| 
13 dicembre 2023

|===