---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: I problemi riscontrati nelle precedenti release dei servizi NetApp Keystone STaaS sono stati risolti nelle release successive. 
---
= Problemi risolti nello STaaS di Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I problemi riscontrati nelle precedenti release dei servizi NetApp Keystone STaaS sono stati risolti nelle release successive.

[cols="3*"]
|===
| Descrizione del problema | Dopo la correzione | Fissato in rilascio 


 a| 
I valori di consumo per gli abbonamenti collegati mostrano numeri negativi errati, causando la visualizzazione non accurata dell'utilizzo totale assegnato.
 a| 
Corretto
 a| 
2025-04-14



 a| 
Impossibile visualizzare i dati storici nella scheda *tendenza consumo* per i livelli di servizio per alcuni abbonamenti.
 a| 
Corretto
 a| 
2025-04-14



 a| 
Opzione *Keystone Subscriptions* mancante da *Watchlist* e l'opzione *numero di abbonamento* da *Reports* sul dashboard di Digital Advisor.
 a| 
Corretto
 a| 
2025-03-19



 a| 
Mancano alcune sottoscrizioni Keystone da *Watchlist* dopo la creazione o la modifica della lista di controllo dal dashboard di Digital Advisor.
 a| 
Corretto
 a| 
2025-03-19



 a| 
Impossibile visualizzare i dati storici nella scheda *tendenza consumo* per i livelli di servizio associati a un abbonamento scaduto e rinnovato con lo stesso ID di rilevamento ma con livelli di servizio diversi.
 a| 
Corretto
 a| 
2025-03-19



 a| 
Impossibile generare report per le sottoscrizioni quando si selezionano più di 10-12 sottoscrizioni dalla scheda *Sottoscrizioni* della pagina *Sottoscrizioni Keystone*.
 a| 
Corretto
 a| 
8 gennaio 2025



 a| 
Impossibile caricare la sottoscheda *Riepilogo volume* nella scheda *volumi e oggetti* per le sottoscrizioni StorageGRID.
 a| 
Corretto
 a| 
21 novembre 2024



 a| 
Il campo *da data* per selezionare l'intervallo di date visualizza una data futura per impostazione predefinita quando si passa alla scheda *Trend consumi*.
 a| 
Corretto
 a| 
4 settembre 2024



 a| 
La TUI di gestione di Keystone Collector non risponde durante la configurazione delle policy AQoS.
 a| 
Corretto
 a| 
7 agosto 2024



 a| 
I grafici di utilizzo visualizzano i dati oltre il periodo di un giorno specificato quando la data corrispondente al giorno corrente è selezionata come data di inizio e di fine per il mese precedente dall'opzione *Trend capacità* nella scheda *Trend capacità*.
 a| 
I grafici di utilizzo ora visualizzano correttamente i dati per il periodo di un giorno specificato.
 a| 
27 giugno 2024



 a| 
I dati di burst maturati nella cronologia non sono disponibili per i livelli di servizio *CVO primario* e *CVO secondario* nella scheda *tendenza capacità* per gli abbonamenti non configurati con una configurazione MetroCluster.
 a| 
Corretto
 a| 
21 giugno 2024



 a| 
Visualizzazione errata del valore consumato di archiviazione oggetti elencato nella scheda *Dettagli volume* per gli abbonamenti AutoSupport.
 a| 
Ora il valore consumato per lo storage a oggetti viene visualizzato correttamente.
 a| 
21 giugno 2024



 a| 
Impossibile visualizzare le informazioni a livello di cluster nella scheda *asset* per le sottoscrizioni AutoSupport configurate con una configurazione MetroCluster.
 a| 
Corretto
 a| 
Giugno, 21, 2024



 a| 
Posizionamento errato dei dati Keystone nei report CSV se la colonna *Nome account* nei report CSV, generata dalla scheda *Trend capacità*, include un nome account con una virgola `(,)`.
 a| 
I dati Keystone sono correttamente allineati nei report CSV.
 a| 
29 maggio 2024



 a| 
Visualizzare l'utilizzo dei burst maturati dalla scheda *tendenza capacità* anche se il consumo è inferiore alla capacità impegnata.
 a| 
Corretto
 a| 
29 maggio 2024



 a| 
Testo della descrizione comando non corretto per l'icona dell'indice *sequenza corrente* nella scheda *tendenza capacità*.
 a| 
Visualizza il testo della descrizione comandi corretto "_la quantità di capacità burst attualmente consumata. Nota: Si tratta del periodo di fatturazione corrente, non dell'intervallo di date selezionato._"
 a| 
28 marzo 2024



 a| 
Le informazioni sui volumi non conformi di AQoS e sui partner MetroCluster non sono disponibili per gli abbonamenti AutoSupport se i dati Keystone non sono presenti per 24 ore.
 a| 
Corretto
 a| 
28 marzo 2024



 a| 
Discrepanza occasionale nel numero di volumi non conformi AQoS elencati nelle schede *Volume Summary* e *Volume Details* se vi sono due livelli di servizio assegnati a un volume che soddisfa la conformità AQoS per un solo livello di servizio.
 a| 
Corretto
 a| 
28 marzo 2024



 a| 
Non sono disponibili informazioni nella scheda *risorse* per gli abbonamenti AutoSupport.
 a| 
Corretto
 a| 
14 marzo 2024



 a| 
Se MetroCluster e FabricPool sono stati abilitati in un ambiente in cui i piani di tasso per il tiering e lo storage a oggetti erano applicabili, i livelli di servizio potrebbero essere derivati in modo errato per i volumi mirror (sia i volumi costituenti che i volumi FabricPool).
 a| 
Ai volumi mirror vengono applicati livelli di servizio corretti.
 a| 
29 febbraio 2024



 a| 
Per alcune sottoscrizioni con un unico livello di servizio o piano tariffario, la colonna di conformità AQoS non era presente nell'output CSV dei report della scheda *volumi*.
 a| 
La colonna conformità è visibile nei report.
 a| 
29 febbraio 2024



 a| 
In alcuni ambienti MetroCluster, sono state rilevate anomalie occasionali nei diagrammi della densità degli IOPS nella scheda *Performance*. Ciò si è verificato a causa di una mappatura imprecisa dei volumi ai livelli di servizio.
 a| 
I grafici sono visualizzati correttamente.
 a| 
29 febbraio 2024



 a| 
L'indicatore di utilizzo per una registrazione del consumo di burst era visualizzato in ambra.
 a| 
L'indicatore viene visualizzato in rosso.
 a| 
13 dicembre 2023



 a| 
L'intervallo di date e i dati nelle schede Trend capacità, utilizzo corrente e prestazioni non sono stati convertiti in fuso orario UTC.
 a| 
L'intervallo di date per la query e i dati in tutte le schede viene visualizzato in ora UTC (fuso orario del server). Il fuso orario UTC viene inoltre visualizzato in corrispondenza di ciascun campo della data nelle schede.
 a| 
13 dicembre 2023



 a| 
Si è verificata una mancata corrispondenza tra la data di inizio e la data di fine tra le schede e i report CSV scaricati.
 a| 
Fisso.
 a| 
13 dicembre 2023

|===