---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: I problemi noti identificano i problemi che potrebbero impedirti di utilizzare Keystone in modo efficace. 
---
= Problemi noti in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I problemi noti identificano i problemi che potrebbero impedirti di utilizzare Keystone STaaS in modo efficace.

Nello STaaS NetApp Keystone sono riportati i seguenti problemi noti:

[cols="3*"]
|===
| Problema noto | Descrizione | Soluzione alternativa 


 a| 
Modifica abbonamento non disponibile
 a| 
L'opzione per modificare la capacità impegnata per le sottoscrizioni Keystone non è attualmente disponibile nella NetApp Console. Questa funzionalità verrà reintrodotta in una versione futura.
 a| 
Nessuno



 a| 
Fattura non corretta a causa della mancata corrispondenza dei dati
 a| 
Una mancata corrispondenza dei dati di consumo per gli abbonamenti AutoSupport comporta la generazione di fatture non corrette, causando inesattezze nella fatturazione.
 a| 
Nessuno



 a| 
Tipo di criterio QoS non corretto
 a| 
Nella scheda *Dettagli volume*, la colonna *tipo criterio QoS* visualizza _QoS_ quando non viene applicato alcun criterio QoS e la colonna conforme mostra _non impostato_, causando un'incoerenza nello stato del criterio QoS visualizzato.
 a| 
Nessuno



 a| 
I dettagli del volume non sono disponibili per le sottoscrizioni principali e collegate
 a| 
La scheda *Volume Summary* mostra zero per il numero totale di volumi, lo stato di conformità QoS, il numero di volumi protetti e la capacità totale consumata per gli abbonamenti primari e secondari collegati.
 a| 
Nessuno

|===