---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Problemi noti in Keystone STaaS 
---
= Problemi noti in Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Problemi noti identificano problemi che potrebbero impedirti di utilizzare in modo efficace i servizi di abbonamento Keystone.

Nello STaaS NetApp Keystone sono stati riportati i seguenti problemi noti.

[cols="3*"]
|===
| Problema noto | Descrizione | Soluzione alternativa 


 a| 
Le informazioni sui volumi non conformi di AQoS e sui partner MetroCluster non sono disponibili per gli abbonamenti AutoSupport.
 a| 
Se per la raccolta dei dati Keystone viene utilizzata la telemetria AutoSupport, il conteggio dei volumi non conformi AQoS elencati nelle schede *Riepilogo volume* e *utilizzo corrente* e le informazioni sui partner MetroCluster non sono disponibili se i dati Keystone non sono presenti per 24 ore.
 a| 
Nessuno



 a| 
Incongruenza occasionale nel numero di volumi non conformi AQoS nella scheda *volumi*.
 a| 
Se a un volume sono assegnati due livelli di servizio che soddisfano la conformità AQoS per un solo livello di servizio, il numero di volumi non conformi AQoS elencati nelle schede *Riepilogo volume* e *Dettagli volume* potrebbe differire.
 a| 
Nessuno



 a| 
Aspetto non corretto della descrizione.
 a| 
La descrizione comando per l'icona dell'indice *sequenza corrente* non viene visualizzata correttamente nella scheda *tendenza capacità*.
 a| 
Fare riferimento al testo della descrizione comandi corretto "_la quantità di capacità burst attualmente consumata. Nota: Si tratta del periodo di fatturazione corrente, non dell'intervallo di date selezionato._"

|===