---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Problemi noti di NetApp Service Engine 
---
= Problemi noti di NetApp Service Engine
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nello STaaS NetApp Keystone sono stati riportati i seguenti problemi noti. Potresti riscontrare problemi di questo tipo durante il provisioning o l'utilizzo dello storage gestito dalle tue iscrizioni a Keystone.

[cols="3*"]
|===
| Problema noto | Descrizione | Soluzione alternativa 


 a| 
Derivato livello di servizio errato per i volumi mirror.
 a| 
Se sia MetroCluster che FabricPool sono abilitati in un ambiente in cui sono applicabili i piani di velocità per il tiering e lo storage a oggetti, i livelli di servizio derivati per i volumi mirror (sia i volumi costituenti che FabricPool) potrebbero non essere corretti.
 a| 
Nessuno.



 a| 
Collegamenti e icone parzialmente visibili nella scheda *Sottoscrizioni*.
 a| 
Alcuni collegamenti e icone, come il collegamento alla scheda *uso corrente* e le descrizioni dei comandi di alcune colonne, sono parzialmente visibili.
 a| 
Non è necessaria alcuna soluzione. I collegamenti funzionano come previsto.

|===