---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Problemi noti identificano problemi che potrebbero impedirti di utilizzare in modo efficace i servizi di abbonamento Keystone. 
---
= Problemi noti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Problemi noti identificano problemi che potrebbero impedirti di utilizzare in modo efficace i servizi di abbonamento Keystone.

Nello STaaS NetApp Keystone sono riportati i seguenti problemi noti:

[cols="3*"]
|===
| Problema noto | Descrizione | Soluzione alternativa 


 a| 
I dettagli del volume non sono disponibili per le sottoscrizioni principali e collegate
 a| 
La scheda *Volume Summary* mostra zero per il numero totale di volumi, lo stato di conformità QoS, il numero di volumi protetti e la capacità totale consumata per gli abbonamenti primari e secondari collegati.
 a| 
Nessuno



 a| 
Impossibile generare report per le sottoscrizioni
 a| 
Quando si selezionano più di 10-12 sottoscrizioni dalla scheda *Sottoscrizioni* della pagina *Sottoscrizioni Keystone*, il report non viene generato quando si fa clic sul pulsante *Scarica CSV* con l'opzione *Includi dati per ogni livello di servizio*.
 a| 
Nessuno

|===