---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nuove funzionalità e miglioramenti di Keystone STaaS. 
---
= Novità di Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp offre funzionalità nuove e migliorate in ogni release dei servizi Keystone STaaS.



== Nuove funzioni e miglioramenti relativi al 09 maggio 2024

I seguenti miglioramenti vengono apportati nella schermata *Iscrizioni Keystone* di Active IQ Digital Advisor (noto anche come Digital Advisor):



=== Nuove colonne nei rapporti CSV

I report CSV della scheda *tendenza capacità* includono ora le colonne *numero di abbonamento* e *Nome account* per migliorare i dettagli.



=== Colonna tipo di utilizzo avanzato

La colonna *tipo di utilizzo* all'interno della scheda *Sottoscrizioni* è stata migliorata per visualizzare gli utilizzi logici e fisici come valori separati da virgole per le sottoscrizioni che coprono i livelli di servizio sia per i file che per gli oggetti.



=== Accedi ai dettagli dello storage a oggetti dalla scheda Dettagli del volume

La scheda *Dettagli volume* all'interno della scheda *volumi e oggetti* fornisce ora dettagli sull'archiviazione degli oggetti insieme alle informazioni sul volume per le sottoscrizioni che includono livelli di servizio sia per i file che per gli oggetti. È possibile fare clic sul pulsante *Dettagli archiviazione oggetti* nella scheda *Dettagli volume* per visualizzare i dettagli.



== Nuove funzioni e miglioramenti relativi al 28 marzo 2024

Il seguente miglioramento è stato apportato nella schermata *Iscrizioni Keystone* del consulente digitale Active IQ:



=== Miglioramento della conformità alle policy QoS nella scheda Volume Details (Dettagli volume)

La scheda *Dettagli volume* all'interno della scheda *volumi e oggetti* offre ora una migliore visibilità della conformità alle policy QoS (Quality of Service). La colonna precedentemente nota come *AQoS* viene rinominata *conforme*, che indica se il criterio QoS è conforme. Inoltre, viene aggiunta una nuova colonna *tipo di criterio QoS*, che specifica se il criterio è fisso o adattivo. Se non è applicabile, la colonna visualizza _non disponibile_. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Nella scheda Volume Summary (Riepilogo volume) vengono visualizzate una nuova colonna e una sottoscrizione semplificata

* La scheda *Volume Summary* nella scheda *Volumes & Objects* include ora una nuova colonna denominata *Protected*. Questa colonna fornisce un conteggio dei volumi protetti associati ai livelli di servizio sottoscritti. Se si fa clic sul numero di volumi protetti, viene visualizzata la scheda *Dettagli volume*, in cui è possibile visualizzare un elenco filtrato di volumi protetti.
* La scheda *Riepilogo volume* viene aggiornata per visualizzare solo le sottoscrizioni di base, esclusi i servizi aggiuntivi. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].




=== Passare alla visualizzazione dei dettagli del burst maturato nella scheda Trend capacità

La descrizione comandi visualizzata quando si passa il mouse sul grafico a barre dell'utilizzo della capacità nella scheda *tendenza capacità* visualizza i dettagli dei burst maturati per il mese corrente. I dettagli non saranno disponibili per i mesi precedenti.



=== Accesso migliorato per visualizzare i dati storici per le iscrizioni a Keystone

Ora puoi visualizzare i dati storici se un abbonamento Keystone viene modificato o rinnovato. È possibile impostare la data di inizio di un abbonamento a una data precedente per visualizzare :

* Dati relativi al consumo e all'utilizzo dei burst maturati dalla scheda *tendenza capacità*,
* Metriche delle prestazioni dei volumi ONTAP dalla scheda *prestazioni*,


tutti i quali mostrano i dati in base alla data selezionata dell'abbonamento.



== Nuove funzioni e miglioramenti per il 29 febbraio 2024

Per questa release, sono stati apportati diversi miglioramenti alla dashboard di Active IQ Digital Advisor (nota anche come Digital Advisor) e alla schermata *Keystone Subscription*:



=== Aggiunta della scheda risorse

La schermata *Iscrizioni Keystone* ora include la scheda *risorse*. Questa nuova scheda fornisce informazioni a livello del cluster in base alle iscrizioni. Per ulteriori informazioni, vedere link:../integrations/assets-tab.html["Scheda risorse"^].



=== Miglioramenti alla scheda volumi e oggetti

Per una maggiore chiarezza dei volumi del sistema ONTAP, nella scheda *volumi* sono stati aggiunti due nuovi pulsanti di tabulazione, *Riepilogo volume* e *Dettagli volume*. La scheda *Volume Summary* fornisce un conteggio complessivo dei volumi associati ai livelli di servizio sottoscritti, incluse le informazioni sullo stato di conformità AQoS e sulla capacità. La scheda *Dettagli volume* elenca tutti i volumi e le relative specifiche. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Migliore esperienza di ricerca su Digital Advisor

I parametri di ricerca nella schermata *Digital Advisor* ora includono i numeri di iscrizione Keystone e le liste di controllo create per le iscrizioni Keystone. È possibile immettere i primi tre caratteri del numero di abbonamento o del nome della lista di controllo. Per ulteriori informazioni, vedere link:../integrations/keystone-aiq.html["Visualizza la dashboard Keystone sul consulente digitale Active IQ"^].



=== Visualizzare la data e l'ora dei dati di consumo

È possibile visualizzare la data e l'ora dei dati di consumo (in UTC) sul vecchio dashboard del widget *Keystone Subscriptions*.



== Nuove funzioni e miglioramenti per il 13 febbraio 2024

Il seguente miglioramento è stato apportato nella schermata *Iscrizioni Keystone* di Active IQ Digital Advisor (noto anche come Digital Advisor).



=== Possibilità di visualizzare gli abbonamenti collegati a un abbonamento principale

Alcuni abbonamenti primari possono avere abbonamenti secondari collegati. In questo caso, il numero di abbonamento principale continuerà a essere visualizzato nella colonna *numero di abbonamento*, mentre i numeri di abbonamento collegati saranno elencati in una nuova colonna *Sottoscrizioni collegate* nella scheda *Sottoscrizioni*. La colonna *Sottoscrizioni collegate* diventa disponibile solo se si dispone di sottoscrizioni collegate ed è possibile visualizzare messaggi informativi che ne informano l'utente.



== Nuove funzioni e migliorie per il 11 gennaio 2024

Scopri le novità di questa versione.

I seguenti miglioramenti sono stati apportati alla schermata *Keystone Subscription* di Active IQ Digital Advisor (noto anche come Digital Advisor).



=== Dati fatturati restituiti per il burst maturato

Le etichette per *Burst maturato* sono ora modificate in *Burst maturato fatturato* nella scheda *Trend capacità*. Selezionando questa opzione è possibile visualizzare i grafici mensili per i dati burst maturati fatturati. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Dettagli sui consumi maturati per piani tariffari specifici

Se si dispone di un abbonamento con piani tariffari con capacità impegnata _zero_, è possibile visualizzare i dettagli sui consumi maturati nella scheda *tendenza capacità*. Selezionando l'opzione *consumo maturato fatturato*, è possibile visualizzare i grafici mensili per i dati di consumo maturato fatturato.



== Nuove funzioni e migliorie per il 15 dicembre 2023

Scopri le novità di questa versione.



=== Possibilità di effettuare ricerche in base alle liste di controllo

Il supporto per le liste di controllo in Active IQ Digital Advisor (noto anche come Digital Advisor) è stato esteso per includere i sistemi Keystone. È ora possibile visualizzare i dettagli degli abbonamenti per più clienti effettuando una ricerca con gli elenchi di controllo. Per ulteriori informazioni sull'utilizzo delle liste di controllo in Keystone STaaS, vedere link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Effettuare una ricerca utilizzando gli elenchi di controllo Keystone"^].



=== Data di conversione in fuso orario UTC

I dati restituiti nelle schede della schermata *Sottoscrizioni Keystone* di Active IQ Digital Advisor vengono visualizzati in ora UTC (fuso orario del server). Quando si immette una data per la query, questa viene automaticamente considerata nel fuso orario UTC. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html["Dashboard e reporting per l'abbonamento Keystone"^].
