---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nuove funzionalità e miglioramenti di Keystone STaaS. 
---
= Novità di Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp offre funzionalità nuove e migliorate in ogni release dei servizi Keystone STaaS.



== Nuove funzioni e miglioramenti per il 13 febbraio 2024

La seguente modifica è stata apportata nella schermata *Iscrizioni Keystone* del consulente digitale Active IQ (noto anche come consulente digitale).



=== Possibilità di visualizzare gli abbonamenti collegati a un abbonamento principale

Alcuni abbonamenti primari possono avere abbonamenti secondari collegati. In questo caso, il numero di abbonamento principale continuerà a essere visualizzato nella colonna *numero di abbonamento*, mentre i numeri di abbonamento collegati saranno elencati in una nuova colonna *Sottoscrizioni collegate* nella scheda *Sottoscrizioni*. La colonna *Sottoscrizioni collegate* diventa disponibile solo se si dispone di sottoscrizioni collegate ed è possibile visualizzare messaggi informativi che ne informano l'utente.



== Nuove funzioni e migliorie per il 11 gennaio 2024

Scopri le novità di questa versione.

Le seguenti modifiche sono state apportate nella schermata *Iscrizioni Keystone* di Active IQ Digital Advisor (noto anche come Digital Advisor).



=== Dati fatturati restituiti per il burst maturato

Le etichette per *Burst maturato* sono ora modificate in *Burst maturato fatturato* nella scheda *Trend capacità*. Selezionando questa opzione è possibile visualizzare i grafici mensili per i dati burst maturati fatturati. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Dettagli sui consumi maturati per piani tariffari specifici

Se si dispone di un abbonamento con piani tariffari con capacità impegnata _zero_, è possibile visualizzare i dettagli sui consumi maturati nella scheda *tendenza capacità*. Selezionando l'opzione *consumo maturato fatturato*, è possibile visualizzare i grafici mensili per i dati di consumo maturato fatturato.



== Nuove funzioni e migliorie per il 15 dicembre 2023

Scopri le novità di questa versione.



=== Possibilità di effettuare ricerche in base alle liste di controllo

Il supporto per le liste di controllo in Active IQ Digital Advisor (noto anche come Digital Advisor) è stato esteso per includere i sistemi Keystone. È ora possibile visualizzare i dettagli degli abbonamenti per più clienti effettuando una ricerca con gli elenchi di controllo. Per ulteriori informazioni sull'utilizzo delle liste di controllo in Keystone STaaS, vedere link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Effettuare una ricerca utilizzando gli elenchi di controllo Keystone"^].



=== Data di conversione in fuso orario UTC

I dati restituiti nelle schede della schermata *Sottoscrizioni Keystone* di Active IQ Digital Advisor vengono visualizzati in ora UTC (fuso orario del server). Quando si immette una data per la query, questa viene automaticamente considerata nel fuso orario UTC. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html["Dashboard e reporting per l'abbonamento Keystone"^].
