---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nuove funzionalità e miglioramenti di Keystone STaaS. 
---
= Novità di Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp offre funzionalità nuove e migliorate in ogni release dei servizi Keystone STaaS.



== Nuove funzioni e miglioramenti per il 29 febbraio 2024

Per questa release, sono stati apportati diversi miglioramenti alla dashboard di Active IQ Digital Advisor (nota anche come Digital Advisor) e alla schermata *Keystone Subscription*:



=== Aggiunta della scheda risorse

La schermata *Iscrizioni Keystone* ora include la scheda *risorse*. Questa nuova scheda fornisce informazioni a livello del cluster in base alle iscrizioni. Per ulteriori informazioni, vedere link:../integrations/assets-tab.html["Scheda risorse"^].



=== Miglioramenti alla scheda volumi e oggetti

Per una maggiore chiarezza dei volumi del sistema ONTAP, nella scheda *volumi* sono stati aggiunti due nuovi pulsanti di tabulazione, *Riepilogo volume* e *Dettagli volume*. La scheda *Volume Summary* fornisce un conteggio complessivo dei volumi associati ai livelli di servizio sottoscritti, incluse le informazioni sullo stato di conformità AQoS e sulla capacità. La scheda *Dettagli volume* elenca tutti i volumi e le relative specifiche. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Migliore esperienza di ricerca su Digital Advisor

I parametri di ricerca nella schermata *Digital Advisor* ora includono i numeri di iscrizione Keystone e le liste di controllo create per le iscrizioni Keystone. È possibile immettere i primi tre caratteri del numero di abbonamento o del nome della lista di controllo. Per ulteriori informazioni, vedere link:../integrations/keystone-aiq.html["Visualizza la dashboard Keystone sul consulente digitale Active IQ"^].



=== Visualizzare la data e l'ora dei dati di consumo

È possibile visualizzare la data e l'ora dei dati di consumo (in UTC) sul vecchio dashboard del widget *Keystone Subscriptions*.



== Nuove funzioni e miglioramenti per il 13 febbraio 2024

Il seguente miglioramento è stato apportato nella schermata *Iscrizioni Keystone* di Active IQ Digital Advisor (noto anche come Digital Advisor).



=== Possibilità di visualizzare gli abbonamenti collegati a un abbonamento principale

Alcuni abbonamenti primari possono avere abbonamenti secondari collegati. In questo caso, il numero di abbonamento principale continuerà a essere visualizzato nella colonna *numero di abbonamento*, mentre i numeri di abbonamento collegati saranno elencati in una nuova colonna *Sottoscrizioni collegate* nella scheda *Sottoscrizioni*. La colonna *Sottoscrizioni collegate* diventa disponibile solo se si dispone di sottoscrizioni collegate ed è possibile visualizzare messaggi informativi che ne informano l'utente.



== Nuove funzioni e migliorie per il 11 gennaio 2024

Scopri le novità di questa versione.

I seguenti miglioramenti sono stati apportati alla schermata *Keystone Subscription* di Active IQ Digital Advisor (noto anche come Digital Advisor).



=== Dati fatturati restituiti per il burst maturato

Le etichette per *Burst maturato* sono ora modificate in *Burst maturato fatturato* nella scheda *Trend capacità*. Selezionando questa opzione è possibile visualizzare i grafici mensili per i dati burst maturati fatturati. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Dettagli sui consumi maturati per piani tariffari specifici

Se si dispone di un abbonamento con piani tariffari con capacità impegnata _zero_, è possibile visualizzare i dettagli sui consumi maturati nella scheda *tendenza capacità*. Selezionando l'opzione *consumo maturato fatturato*, è possibile visualizzare i grafici mensili per i dati di consumo maturato fatturato.



== Nuove funzioni e migliorie per il 15 dicembre 2023

Scopri le novità di questa versione.



=== Possibilità di effettuare ricerche in base alle liste di controllo

Il supporto per le liste di controllo in Active IQ Digital Advisor (noto anche come Digital Advisor) è stato esteso per includere i sistemi Keystone. È ora possibile visualizzare i dettagli degli abbonamenti per più clienti effettuando una ricerca con gli elenchi di controllo. Per ulteriori informazioni sull'utilizzo delle liste di controllo in Keystone STaaS, vedere link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Effettuare una ricerca utilizzando gli elenchi di controllo Keystone"^].



=== Data di conversione in fuso orario UTC

I dati restituiti nelle schede della schermata *Sottoscrizioni Keystone* di Active IQ Digital Advisor vengono visualizzati in ora UTC (fuso orario del server). Quando si immette una data per la query, questa viene automaticamente considerata nel fuso orario UTC. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html["Dashboard e reporting per l'abbonamento Keystone"^].
