---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp offre funzionalità nuove e migliorate in ogni release dei servizi Keystone STaaS. 
---
= Novità di Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp offre funzionalità nuove e migliorate in ogni release dei servizi Keystone STaaS.

I seguenti miglioramenti sono stati introdotti nella schermata *Keystone Subscription* di Active IQ Digital Advisor (noto anche come Digital Advisor):



== 12 dicembre 2024



=== Rinominata colonna logica utilizzata

La colonna *logica utilizzata* nella scheda *Dettagli volume* all'interno di *volumi e oggetti* è ora rinominata *Keystone Logical used*.



=== Scheda risorse avanzate

La scheda *risorse* nella schermata *Sottoscrizioni Keystone* contiene ora due nuove sotto-schede: *ONTAP* e *StorageGRID*. Queste sotto-schede offrono informazioni dettagliate a livello del cluster per ONTAP e informazioni a livello di grid per StorageGRID in base alle tue iscrizioni. Per ulteriori informazioni, fare riferimento a link:../integrations/assets-tab.html["Scheda risorse"^].



=== Nuova opzione Nascondi/Mostra colonne

La scheda *Dettagli volume* all'interno di *volumi e oggetti* include ora l'opzione *Nascondi/Mostra colonne*. Questa opzione consente di selezionare o deselezionare le colonne per personalizzare l'elenco tabulare dei volumi in base alle proprie preferenze. Per ulteriori informazioni, fare riferimento a link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



== 21 novembre 2024



=== Burst maturato fatturato migliorato

È ora possibile visualizzare i dati sull'utilizzo del bursting maturato su base trimestrale tramite l'opzione *Burst maturato fatturato* se si è scelto un periodo di fatturazione trimestrale. Per ulteriori informazioni, fare riferimento a link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Nuove colonne nella scheda Dettagli volumi

Per migliorare la chiarezza nel calcolo dell'utilizzo logico, sono state aggiunte due nuove colonne alla scheda *Dettagli volume* nella scheda *volumi e oggetti*:

* *AFS logico*: Visualizza la capacità logica utilizzata dal file system attivo del volume.
* *Istantanea fisica*: Visualizza lo spazio fisico utilizzato dagli snapshot.


Queste colonne forniscono una maggiore chiarezza nella colonna *logica utilizzata*, che mostra la capacità logica combinata utilizzata dal file system attivo del volume e lo spazio fisico utilizzato dagli snapshot.



== 11 novembre 2024



=== Generazione di rapporti migliorata

Ora puoi generare un report consolidato per visualizzare i dettagli dei tuoi dati Keystone utilizzando la funzionalità Report in Digital Advisor. Per ulteriori informazioni, fare riferimento a link:../integrations/aiq-keystone-details.html#generate-consolidated-report["Generare un rapporto consolidato"^].



== 10 luglio 2024



=== Modifiche alle etichette

L'etichetta *uso corrente* viene modificata in *consumo corrente* e *tendenza capacità* viene modificata in *tendenza consumo*.



=== Barra di ricerca per gli abbonamenti

Il menu a discesa *Sottoscrizioni* in tutte le schede della schermata *Sottoscrizioni Keystone* include ora una barra di ricerca. È possibile cercare sottoscrizioni specifiche elencate nel menu a discesa *Sottoscrizioni*.



== 27 giugno 2024



=== Visualizzazione coerente dell'abbonamento

La schermata *Iscrizioni Keystone* viene aggiornata per visualizzare il numero di abbonamento selezionato in tutte le schede.

* Quando viene aggiornata una scheda nella schermata *Sottoscrizioni Keystone*, la schermata passa automaticamente alla scheda *Sottoscrizioni* e ripristina tutte le schede alla prima sottoscrizione elencata nel menu a discesa *sottoscrizione*.
* Se l'abbonamento selezionato non è iscritto alle metriche di prestazione, la scheda *prestazioni* visualizzerà il primo abbonamento elencato nel menu a discesa *abbonamento* al momento della navigazione.




== 29 maggio 2024



=== Indicatore burst migliorato

L'indicatore *Burst* nell'indice grafico di utilizzo è stato migliorato per visualizzare il valore percentuale del limite burst. Questo valore cambia a seconda del limite di burst concordato per un abbonamento. È inoltre possibile visualizzare il valore del limite di burst nella scheda *Sottoscrizioni* passando con il mouse sull'indicatore *utilizzo burst* nella colonna *Stato utilizzo*.



=== Aggiunta di livelli di servizio

I livelli di servizio *CVO primario* e *CVO secondario* sono inclusi per supportare Cloud Volumes ONTAP per gli abbonamenti che hanno piani tariffari con zero capacità impegnata o quelli configurati con un cluster metro.

* È possibile visualizzare il grafico dell'utilizzo della capacità per questi livelli di servizio dal vecchio dashboard del widget *Keystone Subscription* e dalla scheda *Capacity Trend*, nonché informazioni dettagliate sull'utilizzo dalla scheda *utilizzo corrente*.
* Nella scheda *Sottoscrizioni*, questi livelli di servizio vengono visualizzati come `CVO (v2)` Nella colonna *tipo di utilizzo*, che consente l'identificazione della fatturazione in base a questi livelli di servizio.




=== Funzione di ingrandimento per burst a breve termine

La scheda *Trend capacità* include ora una funzione di zoom per visualizzare i dettagli delle sequenze di burst a breve termine nei grafici di utilizzo. Per ulteriori informazioni, vedere link:../integrations/capacity-trend-tab.html["Scheda Trend capacità"^].



=== Visualizzazione migliorata degli abbonamenti

La visualizzazione predefinita delle sottoscrizioni è stata migliorata per ordinare in base all'ID di rilevamento. Le sottoscrizioni nella scheda *Sottoscrizioni*, inclusi i rapporti a discesa *sottoscrizione* e CSV, verranno ora visualizzate in base alla sequenza alfabetica degli ID di tracciamento, seguendo l'ordine di a, A, b, B e così via.



=== Display burst migliorato

La descrizione comandi visualizzata quando si passa il mouse sul grafico a barre dell'utilizzo della capacità nella scheda *tendenza capacità* visualizza ora il tipo di burst maturato in base alla capacità impegnata. Esso differenzia tra burst accantonato provvisorio e fatturato, indicando *consumo accantonato provvisorio* e *consumo maturato fatturato* per abbonamenti con piani tasso di capacità impegnati zero, e *Burst accantonato provvisorio* e *Burst maturato fatturato* per quelli con capacità impegnata diversa da zero.



== 09 maggio 2024



=== Nuove colonne nei rapporti CSV

I report CSV della scheda *tendenza capacità* includono ora le colonne *numero di abbonamento* e *Nome account* per migliorare i dettagli.



=== Colonna tipo di utilizzo avanzato

La colonna *tipo di utilizzo* all'interno della scheda *Sottoscrizioni* è stata migliorata per visualizzare gli utilizzi logici e fisici come valori separati da virgole per le sottoscrizioni che coprono i livelli di servizio sia per i file che per gli oggetti.



=== Accedi ai dettagli dello storage a oggetti dalla scheda Dettagli del volume

La scheda *Dettagli volume* all'interno della scheda *volumi e oggetti* fornisce ora dettagli sull'archiviazione degli oggetti insieme alle informazioni sul volume per le sottoscrizioni che includono livelli di servizio sia per i file che per gli oggetti. È possibile fare clic sul pulsante *Dettagli archiviazione oggetti* nella scheda *Dettagli volume* per visualizzare i dettagli.



== 28 marzo 2024



=== Miglioramento della conformità alle policy QoS nella scheda Volume Details (Dettagli volume)

La scheda *Dettagli volume* all'interno della scheda *volumi e oggetti* offre ora una migliore visibilità della conformità alle policy QoS (Quality of Service). La colonna precedentemente nota come *AQoS* viene rinominata *conforme*, che indica se il criterio QoS è conforme. Inoltre, viene aggiunta una nuova colonna *tipo di criterio QoS*, che specifica se il criterio è fisso o adattivo. Se non è applicabile, la colonna visualizza _non disponibile_. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Nella scheda Volume Summary (Riepilogo volume) vengono visualizzate una nuova colonna e una sottoscrizione semplificata

* La scheda *Volume Summary* nella scheda *Volumes & Objects* include ora una nuova colonna denominata *Protected*. Questa colonna fornisce un conteggio dei volumi protetti associati ai livelli di servizio sottoscritti. Se si fa clic sul numero di volumi protetti, viene visualizzata la scheda *Dettagli volume*, in cui è possibile visualizzare un elenco filtrato di volumi protetti.
* La scheda *Riepilogo volume* viene aggiornata per visualizzare solo le sottoscrizioni di base, esclusi i servizi aggiuntivi. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].




=== Passare alla visualizzazione dei dettagli del burst maturato nella scheda Trend capacità

La descrizione comandi visualizzata quando si passa il mouse sul grafico a barre dell'utilizzo della capacità nella scheda *tendenza capacità* visualizza i dettagli dei burst maturati per il mese corrente. I dettagli non saranno disponibili per i mesi precedenti.



=== Accesso migliorato per visualizzare i dati storici per le iscrizioni a Keystone

Ora puoi visualizzare i dati storici se un abbonamento Keystone viene modificato o rinnovato. È possibile impostare la data di inizio di un abbonamento a una data precedente per visualizzare :

* Dati relativi al consumo e all'utilizzo dei burst maturati dalla scheda *tendenza capacità*,
* Metriche delle prestazioni dei volumi ONTAP dalla scheda *prestazioni*,


tutti i quali mostrano i dati in base alla data selezionata dell'abbonamento.



== 29 febbraio 2024



=== Aggiunta della scheda risorse

La schermata *Iscrizioni Keystone* ora include la scheda *risorse*. Questa nuova scheda fornisce informazioni a livello del cluster in base alle iscrizioni. Per ulteriori informazioni, vedere link:../integrations/assets-tab.html["Scheda risorse"^].



=== Miglioramenti alla scheda volumi e oggetti

Per una maggiore chiarezza dei volumi del sistema ONTAP, nella scheda *volumi* sono stati aggiunti due nuovi pulsanti di tabulazione, *Riepilogo volume* e *Dettagli volume*. La scheda *Volume Summary* fornisce un conteggio complessivo dei volumi associati ai livelli di servizio sottoscritti, incluse le informazioni sullo stato di conformità AQoS e sulla capacità. La scheda *Dettagli volume* elenca tutti i volumi e le relative specifiche. Per ulteriori informazioni, vedere link:../integrations/volumes-objects-tab.html["Scheda volumi  oggetti"^].



=== Migliore esperienza di ricerca su Digital Advisor

I parametri di ricerca nella schermata *Digital Advisor* ora includono i numeri di iscrizione Keystone e le liste di controllo create per le iscrizioni Keystone. È possibile immettere i primi tre caratteri del numero di abbonamento o del nome della lista di controllo. Per ulteriori informazioni, vedere link:../integrations/keystone-aiq.html["Visualizza la dashboard Keystone sul consulente digitale Active IQ"^].



=== Visualizzare la data e l'ora dei dati di consumo

È possibile visualizzare la data e l'ora dei dati di consumo (in UTC) sul vecchio dashboard del widget *Keystone Subscriptions*.



== 13 febbraio 2024



=== Possibilità di visualizzare gli abbonamenti collegati a un abbonamento principale

Alcuni abbonamenti primari possono avere abbonamenti secondari collegati. In questo caso, il numero di abbonamento principale continuerà a essere visualizzato nella colonna *numero di abbonamento*, mentre i numeri di abbonamento collegati saranno elencati in una nuova colonna *Sottoscrizioni collegate* nella scheda *Sottoscrizioni*. La colonna *Sottoscrizioni collegate* diventa disponibile solo se si dispone di sottoscrizioni collegate ed è possibile visualizzare messaggi informativi che ne informano l'utente.



== 11 gennaio 2024



=== Dati fatturati restituiti per il burst maturato

Le etichette per *Burst maturato* sono ora modificate in *Burst maturato fatturato* nella scheda *Trend capacità*. Selezionando questa opzione è possibile visualizzare i grafici mensili per i dati burst maturati fatturati. Per ulteriori informazioni, vedere link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst["Visualizza bursting maturato fatturato"^].



=== Dettagli sui consumi maturati per piani tariffari specifici

Se si dispone di un abbonamento con piani tariffari con capacità impegnata _zero_, è possibile visualizzare i dettagli sui consumi maturati nella scheda *tendenza capacità*. Selezionando l'opzione *consumo maturato fatturato*, è possibile visualizzare i grafici mensili per i dati di consumo maturato fatturato.



== 15 dicembre 2023



=== Possibilità di effettuare ricerche in base alle liste di controllo

Il supporto per le liste di controllo in Digital Advisor è stato esteso per includere i sistemi Keystone. È ora possibile visualizzare i dettagli degli abbonamenti per più clienti effettuando una ricerca con gli elenchi di controllo. Per ulteriori informazioni sull'utilizzo delle liste di controllo in Keystone STaaS, vedere link:../integrations/keystone-aiq.html#search-by-keystone-watchlists["Ricerca per elenchi di controllo Keystone"^].



=== Data di conversione in fuso orario UTC

I dati restituiti nelle schede della schermata *Keystone Subscriptions* di Digital Advisor vengono visualizzati in ora UTC (fuso orario del server). Quando si immette una data per la query, questa viene automaticamente considerata nel fuso orario UTC. Per ulteriori informazioni, vedere link:../integrations/aiq-keystone-details.html["Dashboard e reporting per l'abbonamento Keystone"^].
